### ISSUE TITLE
manyToMany in \DoctrineModule\Form\Element\ObjectMultiCheckbox and related elements

### ISSUE THREAD

**Issue by acnb** [doctrine/DoctrineModule#166]
I'm using \DoctrineModule\Form\Elements in my Zend2 application. I use \Zend\Form\Form::bind(EntityA) to connect the form to EntityA. Everything works well if the association between the target_class EntityB and EntityA is manyToOne. However, if the association is manyToMany I get the error 

Argument 1 passed to Application\Entity\EntityA::addEntityB() must be an instance of Application\Entity\EntityB, instance of Doctrine\Common\Collections\ArrayCollection given, called in ...\vendor\doctrine\doctrine-module\src\DoctrineModule\Stdlib\Hydrator\Strategy\AllowRemoveByValue.php on line 61

I believe something like Application\Entity\EntityA::SETEntityB() has to be called instead? (I know, that by default there are no setters for ..toMany associations.)

**Comment by IgorDePaula** [comment]
I received the error:

Warning: spl_object_hash() expects parameter 1 to be object, string given in C:\wamp\www\tandle.local\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php on line 1339

I put the checkboxes in the form and to update i received this error.

In my controller are this code:

´´´php

if ($this->getRequest()->isPost()) {
            $data = $this->getRequest()->getPost();
            
            $form->setData($data);
            if ($form->isValid()) {
                $disciplina->populate($data->toArray());
                $disciplina->store();
                if (count($data['curso']) > 0) {
                    foreach ($data['curso'] as $idcurso) {
                        $c = $curso->getById($idcurso);
                        $c->addDisciplina($disciplina);
                        $disciplina->addCurso($c);
                    }
                    if ($data['iddisciplina'] > 0) {
                        $this->getEntityManager()->persist($disciplina);
                        $this->getEntityManager()->persist($c);
                        $this->getEntityManager()->flush();
                    } else {
                        $this->getEntityManager()->merge($disciplina);
                        $this->getEntityManager()->merge($c);
                        $this->getEntityManager()->flush();
                    }
                }
            } else {
                $errors = $form->getMessages();
            }
        }

´´´
