### ISSUE TITLE
Cross-database joins

### ISSUE THREAD

**Issue by jamiehannaford** [doctrine/DoctrineModule#173]
Does DoctrineModule support cross-database joins? In my ZF2 application I have two modules, each with its own database - controlled by a separate Entity Manager.

Is there any way to link an Entity in one module to another? I've tried this in Client\Entity\Website:

``` php
/**
 * A website.
 *
 * @ORM\Entity
 * @ORM\Table(name="website")
 * ...
 * @property int $server
 */
class Website extends BaseEntity {

    // Other class vars ... 

    /**
     * @ORM\Column(type="integer")
     * @ORM\ManyToOne(targetEntity="Server\Entity\Server", inversedBy="websites")
     * @ORM\JoinColumn(name="server_id", referencedColumnName="id")
     */
    protected $server;
```

And this in my Server\Entity\Server entity:

``` php
/**
 * A server.
 *
 * @ORM\Entity
 * @ORM\Table(name="server")
 * ...
 * @property string $websites
 */
class Server extends BaseEntity {

    // Other class vars...

    /**
     * @ORM\OneToMany(targetEntity="Client\Entity\Website", mappedBy="server")
     */
    protected $websites;
```

But it results in this error:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'users.server' doesn't exist`

**Comment by afilina** [comment]
@Ocramius How would you go about using a variable `dbname` in the `@Table` annotation? Is there a listener somewhere to override the name before the SQL is generated?

In the legacy code I have, the dbname changes based on the user that is connected.
