### ISSUE TITLE
ObjectSelect with "multiple"

### ISSUE THREAD

**Issue by ThaDafinser** [doctrine/DoctrineModule#215]
Hello,

the ObjectSelect works generally well with "multiple" select. (but i don't know if it's tested already)
You can add or remove multiple relations very well.

But when you want to unselect all selected in the form, where won't be a submit of the select field.
With no POST doctrine don't remove the relations.

Test case: Create a entry with one or more relation. Try to edit this entry and remove there all relations -> it won't remove the relations.

``` php
$this->add(array(
    'type' => 'DoctrineModule\Form\Element\ObjectSelect',
    'name' => 'modules',
    'attributes' => array(
        'id' => 'selectModules',
        'multiple' => true,
        'style' => 'width: 100%',

        'data-placeholder' => 'Modules'
    ),
    'options' => array(
        'object_manager' => $entityManager,
        'target_class' => 'LispMachine\Entity\Module',
        'property' => 'name'
    )
));
```

**Comment by elchristo** [comment]
Hi, same behaviour here with ObjectMultiCheckbox and no element selected.
I've tried to use the "unselected_value" option (bakura10/zf2@469ddd8) which still writes a default value to the database. Instead I'd like to clear the collection and delete these table rows.

@bakura10 I think as well it's rather a problem of the hydrator.
I've figured out that the issue appears when the POST data contains an empty string for the multiple select element (when nothing selected). When I simply change this to an empty array everything is working fine.
Maybe an empty string should by simply interpretated as an empty array for the multiple select elements ?

**Comment by pogwizdkrzysztof** [comment]
```
    /**
	 * @var ArrayCollection
	 * 
     * @ORM\ManyToMany(targetEntity="Posts\Entity\Tag", inversedBy="posts")
     * @ORM\JoinTable(name="post_tag",
	 * joinColumns={@ORM\JoinColumn(name="post_id", referencedColumnName="id")},
	 * inverseJoinColumns={@ORM\JoinColumn(name="tag_id", referencedColumnName="id")}
	 * )
     * @Annotation\Type("DoctrineModule\Form\Element\ObjectSelect")
     * @Annotation\Attributes({"multiple":true, "required":false})
	 * @Annotation\Required(false)
	 * @Annotation\AllowEmpty
     * @Annotation\Options({
     * "label":"Tags:",
     * "target_class":"Posts\Entity\Tag",
	 * "required":"false"
     * })
     */
    protected $tags;
```

Works for me. Just type:
```
"required":"false"
```
in "Options" / "options"

**Comment by PoetikDragon** [comment]
Don't know why this is closed when its still an issue

**Comment by TomHAnderson** [comment]
@PoetikDragon the author closed it.

**Comment by ThaDafinser** [comment]
For me it's not an issue anymore / i don't need it anymore.

If you still need it, just open a new issue and refer to this one.
