### ISSUE TITLE
Tag 0.8.0 missing for "doctrine/doctrine-orm-module" dependency

### ISSUE THREAD

**Issue by eggnaube** [doctrine/DoctrineModule#222]
The composer module "doctrine/doctrine-orm-module" requires tag 0.8.\* for "doctrine/doctrine-module" which is missing (replaced by 0.9.0).

**Comment by ashahid007** [comment]
i have below composer.json and it shows me same subject error.

{
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for ZF2",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://framework.zend.com/",
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.3.3",
        "ext-mongo": ">=1.2.12,<1.7-dev",
        "zendframework/zendframework": "~2.4",
        "doctrine/doctrine-module":          "~0.8",
        "doctrine/data-fixtures": ">0.2",
        "doctrine/doctrine-mongo-odm-module": "0.8.2",
        "doctrine/doctrine-orm-module": ">=2.5,<2.7",
        "dompdf/dompdf" : "0.7.*"
    },
    "require-dev": {
        "phpunit/phpunit": "3.7.*"
    }
}


its working in linux but not working in wamp windows.
Please provide any solution.

**Comment by Ocramius** [comment]
@eggnaube not an issue of the repository: ask a question on stackoverflow or ask on irc.freenode.net in the `#composer` channel.
