### ISSUE TITLE
exctractByValue does not support isMethod()

### ISSUE THREAD

**Issue by sparrowek** [doctrine/DoctrineModule#281]
It is common (or more natural) to name accessor methods for boolean properties as isProperty() eg. isActive() instead of getActive(). Unfortunately DoctrineObject hydrator does not support this in following code:

protected function extractByValue($object)
    {
        $fieldNames = array_merge($this->metadata->getFieldNames(), $this->metadata->getAssociationNames());
        $methods    = get_class_methods($object);

```
    $data = array();
    foreach ($fieldNames as $fieldName) {
        $getter = 'get' . ucfirst($fieldName);
```

It would be nice to have support for this.

**Comment by DannyvdSluijs** [comment]
@Ocramius with the current code base at version 1.0.1 I can see there is support for is***** methods. Guess this can be closed?

**Comment by driehle** [comment]
Please open an issue at https://github.com/doctrine/doctrine-laminas-hydrator if this is still relevant.
