### ISSUE TITLE
Adding more data ObjectSelect

### ISSUE THREAD

**Issue by guilherme-santos** [doctrine/DoctrineModule#283]
Hi,
I'm using a ObjectSelect but I need to make some custom logic in javascript, to do that I need some data-* attributes, for example:
If I have a list of colors (red, green, blue and black) and when I change the color in javascript i would like to change using the attribute data-rgb of selected option..

I thought in add a new option like 'property' and pass an array with the properties that i would like to export and all these properties will be created using data-* attribute of html..
```<select>
<option value='black' data-rgb='000'>BACKGROUND BLACK</option>
<option value='red' data-rgb='f00'>BACKGROUND RED</option>
<option value='green' data-rgb='0f0'>BACKGROUND GREEN</option>
<option value='blue' data-rgb='00f'>BACKGROUND BLUE</option>
</select>
```

Ok, can i use value to put the rgb color, but if I want more properties?

**Comment by manuakasam** [comment]
Alright, since I've just implemented `<optgroup>` support, this here seems to fall in line pretty well. I'd implement it in this fashion:

```php
$this->add(
    array(
        'type' => 'DoctrineModule\Form\Element\ObjectSelect',
        'name' => 'name',
        'options' => array(
            'object_manager'      => $this->getObjectManager(),
            'target_class'        => 'Module\Entity\SomeEntity',
            'property'            => 'property',
            'data_attributes' => [
                'x' => 'propertyX',
                'y' => 'propertyY'
            ]
        ),
    )
);
```

that would then render the options like usual including the data attributes with respective values

```html
<option value="foo" data-x="returnFromGetPropertyX" data-y="returnFromGetPropertyY">property</option>
```

**Comment by gianarb** [comment]
Oh yes! :) Good implementation in my opinion

**Comment by manuakasam** [comment]
@gianarb just noticed that this behavior is already present in master branch

```
'options' => [
    'option_attributes' => [
        ['data-id' => 'getId']
    ]
]
```

Not sure why the implementor had to nest this inside an additional array but it works like this. So as far as the master branch is concerned this issue here can be closed.

**Comment by gianarb** [comment]
mm ok I don't remember the history of this feature.. Thanks for this info.. 
We can add this example into the docs! :)
