### ISSUE TITLE
NullObject Design Pattern Support

### ISSUE THREAD

**Issue by foush** [doctrine/DoctrineModule#305]
I'd like to implement the NullObject design pattern for Doctrine entities in a project. I'm not sure what the best approach for adding this is, my current lead is adding a HydratorStrategy which would check if a property is a non-literal. If so, and if it would be hydrated with a 'null' value, instead set the value to a null-object equivalent. Is there any easier/more correct way of doing this?

**Comment by Richard87** [comment]
Hi, I would also like this...

I have 1 "Null object" `MissingAnswer`, that I use in my code, but calling "flush()" on a entity that have a relation to a null object throws an exception, I have solved it with this:

```
    /** @ORM\PreFlush() */
    public function preFlush() {
        $this->missingAnswers = [];
        foreach ($this->answers as $answer) {
            if ($answer instanceof MissingAnswer) {
                $this->missingAnswers[] = $answer;
                $this->answers->removeElement($answer);
            }
        }
    }

    /** @ORM\PostUpdate() @ORM\PostPersist */
    public function postFlush() {
        foreach ($this->missingAnswers as $answer)
            $this->answers->add($answer);
    }
```

What I would love is an annonation `@ORM\IgnoreEntity()` or similar

**Comment by Ocramius** [comment]
The ORM/ODM do not support this pattern internally, so you'd just land into
a massive amount of pain if you implement it.
