### ISSUE TITLE
Update AllowRemoveByValue to empty $collection array for array_udiff

### ISSUE THREAD

**Issue by akiiiii** [doctrine/DoctrineModule#323]
https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Stdlib/Hydrator/Strategy/AllowRemoveByValue.php
throws an error if 
$collection = $this->getCollectionFromObjectByValue(); is null

**Comment by driehle** [comment]
Please open an issue at https://github.com/doctrine/doctrine-laminas-hydrator if this is still relevant.
