### ISSUE TITLE
"Hydrator" tutorial incomplete

### ISSUE THREAD

**Issue by cassettenjockey** [doctrine/DoctrineModule#327]
Hi guys,

i'm new to zf2 and doctrine2 but i decided to make it part of my master thesis... i regret that, but anyway... after hours i finally figured out how to handle the hydrator with formfieldsets...

as far as i can tell, the BlogPost Entity is incomplete:
    /**
     \* @ORM\Column(type="string")
     \* @var unknown
     */
    protected $title;

 public function setTitle($title) {
        $this->title = $title;
    }

```
public function getTitle() {
    return $this->title;
}
```

is missing... in BlogPostFieldset it is added as an InputField.

it took me quite some time to work through that tutorial. because its kind of complex, it would be great if you could provide a complete example-code based on a zend skeleton application (including folder structure, view template, use-statements and so on).

**Comment by driehle** [comment]
Please see https://github.com/doctrine/doctrine-laminas-hydrator for the hydrator and its documentation.
