### ISSUE TITLE
hydrator a-complete-example-using-zendform

### ISSUE THREAD

**Issue by daslicht** [doctrine/DoctrineModule#347]
Hello, 

...

Missing $title variable ?:
https://github.com/doctrine/DoctrineModule/blob/master/docs/hydrator.md#a-complete-example-using-zendform

Shouldnt the class BlogPost include a variable called $title ?

...

is there somewhere the full code of a Hydrator Zendform Example?

When I try to post my form it is never be valid.

Cheers
Marc

**Comment by bartoszzajac** [comment]
@tad3j I have same problem (blank page, it fails in InvokableFactory.php when trying to instantinate fieldset class) How did you manage to resolve this problem. I can't believe that it is still here since 2013.

**Comment by driehle** [comment]
Please see the docs of [doctrine/doctrine-laminas-hydator](https://github.com/doctrine/doctrine-laminas-hydrator) for a full laminas-form example.

Edit: Fixed typo.

**Comment by armenio** [comment]
> Please see the docs of [doctrine/doctrine-laminas-hydator](https://github.com/doctrine/doctrine-laminas-hydator) for a full laminas-form example.

https://github.com/doctrine/doctrine-laminas-hydrator
