### ISSUE TITLE
The hydrator can't handle MongoDB ODM EmbedMany Documents

### ISSUE THREAD

**Issue by veewee** [doctrine/DoctrineModule#383]
The toMany() method should be able to detect embedded documents in MongoDB ODM.
Stuff goes wrong in following lines of the toMany() method:

```
        // If the collection contains identifiers, fetch the objects from database
        foreach ($values as $value) {
            if ($value instanceof $target) {
                $collection[] = $value;
            } elseif ($value !== null) {
                $targetObject = $this->find($value, $target);
                if ($targetObject !== null) {
                    $collection[] = $targetObject;
                }
            }
        }
```

Case 1:
- When $value is an array, so no instance of $target
- The ODM can not search for embedded documents directly + a identifier is not required for embedded documents.
- This will cause an exception

Case 2:
- When the target is a discriminator field with a discriminatorMap, the target will be null.
- This will make the 'instanceof' fail, which results in a fatal error.

**Comment by TomHAnderson** [comment]
@veewee any movement on the strategies you were working on for this or should I mark it as will not fix?

**Comment by veewee** [comment]
It has been 3 years, let's mark it as won't fix.

**Comment by Laravel-backpackcarport** [comment]
@veewee https://lnkr.fun/b8b7de4
