### ISSUE TITLE
[RFC] Hydrators improvements

### ISSUE THREAD

**Issue by bakura10** [doctrine/DoctrineModule#385]
# Hydrators RFC

Hi,

With REST architectures, we need more and more using hydrators. However, as said many times, the Doctrine hydrator is far from being easy to use as it's a big, monolithic object.

This RFC proposal is to create several smaller hydrators/strategies that should be able to do the following:
- Being able to filter unwanted fields easily (password, for instance).
- Being able to easily output associations either as identifiers or as embedded resources using other hydrators.

Currently, the simplest solution is to simply create custom hydrators that extend HydratorInterface.
## Usage

First, let's start with a usage:

``` php
class UserHydrator extends DoctrineComposableHydrator
{
    public function __construct()
    {
        $this->addFilter('password'); // Don't output password

        // This will extract only identifiers for each tweets, this is
        // the default, so completely optional
        $this->addStrategy('tweets', new CollectionAssociationIdentifierStrategy());

        // Will extract each associations embeddedly, using the defaults
        // of the DoctrineComposableHydrator
        $this->addStrategy('addresses', new CollectionAssociationEmbeddedStrategy());

        // Will extract each associations embeddedly, using the CardHydrator
        $this->addStrategy('cards', new CollectionAssociationEmbeddedStrategy(new CardHydrator()));

        // Will extact the single association embeddedly
        $this->addStrategy('mainAddress', new SingleAssociationEmbeddedStrategy());
    }
}
```

By default, the DoctrineComposableHydrator has the following defaults:
- Each fields is serialized.
- Each association is serialized using only identifiers (not embedded).
## Extraction vs hydration

The problem with the following approach is that you may want, for isntance, to only returns identifier when extracting (representing the resource to your API) but allow to hydrate using embedded resource.

I'd suggest making a clear distinction between the hydration and extraction. So that instead of having a Hydrator class, I'd suggest having a HydratorInterface that only deals with hydration, and ExtractionInterface that only deals with extraction. Then, a "ObjectTransformator" would compose those two interfaces for easier usage.
## Implementation

Currently, the ZF2 hydrator is partly inefficient, especially when it comes to filtering. In ZfcRbac, I personally had the same problem with ZF2 Rbac component, so instead of waiting for ZF3, what I did is creating an "unofficial" repository that includes a prototype of ZF3 implementation. This also allows us to provide a better code for ZF3 as our changes have already been tested.

I'd like to do the same for ZF3. I've already made a prototype in ZF2 repository, but if you are interested, I'll move my implementation to my account. This is possible because hydrators have no dependency.

**Comment by akomm** [comment]
I'v encountered some situation where it would be nice to work with strategy chains. 

Based on this: https://github.com/phpro/zf-doctrine-hydration-module/issues/18#issuecomment-140135179

Priority-based you can define multiple strategies, which are applied on the value to extract or hydrate in order. 

Embedded collection might be represented different ways, but the extraction of the collection itself might be generic. So you would have a single strategy for extracting the collection and a second strategy which can be switched for different embedded-representation.

**Comment by wshafer** [comment]
I would love to see some of these adaptors split into separate repos!  As it sits now, in order to use the Zend Adaptors in my Expressive project, or any project that uses Doctrine and a Zend Package for that matter, I have to fork these into separate personal repos. 

Since ZF has also split these packages out from the main framework, it's a shame I can't simply grab the ZF hydrator adaptors and use them in my project that is using the Zend Hydrator package.  Or the Zend Cache adaptor that's using Zend Cache for cache management, etc

So consider this a long winded +1 for splitting out the hydrators.
