### ISSUE TITLE
Hydrator sometimes fails with entity object with refs

### ISSUE THREAD

**Issue by kusmierz** [doctrine/DoctrineModule#389]
Have two entities, project and offer:

``` php
/**
 * Project
 *
 * @ORM\Table(name="project")
 * @ORM\Entity
 */
class Project
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Offer
     *
     * @ORM\ManyToOne(targetEntity="Offer")
     * @ORM\JoinColumn(name="offer_id", referencedColumnName="id", nullable=false)
     */
    private $offer;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="ProjectPage", mappedBy="project", cascade={"all"}, orphanRemoval=true, fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"id" = "ASC"})
     */
    private $pages;
```

``` php
/**
 * Offer
 *
 * @ORM\Table(name="offer")
 * @ORM\Entity
 */
class Offer
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="pages", type="smallint", nullable=true)
     */
    private $pages;
```

trying hydrate following data:

``` php
$data = [
   'id' => ...
   'offer' => [
      'id' => ...
      'pages' => null
   ],
   'pages' => [
      // ...
   ]
]
```

in this way:

``` php
        $project = new \Project();
        $hydrator = new \DoctrineModule\Stdlib\Hydrator\DoctrineObject($this->entityManager);

        return $hydrator->hydrate($data, $project);
```

but I think there is problem with strategies... 

`\DoctrineModule\Stdlib\Hydrator\DoctrineObject::hydrate` do `prepare` and `prepareStrategies`, which saves correct strategies for `$project` in my case (for field "pages" in example). Next is `DoctrineObject::hydrateByValue` hydrating my Offer entity:

https://github.com/doctrine/DoctrineModule/blob/e85b86e651d4b12b3ca1b5262d8b6b63b9ae52ac/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L257

``` php
$value = $this->toOne($target, $this->hydrateValue($field, $value, $data));
```

`toOne` has `hydrate` method on https://github.com/doctrine/DoctrineModule/blob/e85b86e651d4b12b3ca1b5262d8b6b63b9ae52ac/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L380 which is preparing itself again with their strategies... but now the object is not Project Entity, but Offer! It has old `$this->strategies` (with old Project::$pages strategy), but here is wrong (as Offer::$pages is integer).

Anyway, as log as you don't have same field names with different types... it's quite ok. But here, `DoctrineObject:::hydrate` is trying to hydrate my Offer::$pages as Project::$pages, but first field is integer, and second one - a reference!

I think to fix it, you should change the line https://github.com/doctrine/DoctrineModule/blob/e85b86e651d4b12b3ca1b5262d8b6b63b9ae52ac/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L380:

``` php
            $hydrator = new $this($this->objectManage, $this->byValue);
            return $hydrator->hydrate($value, $object);
```

**Comment by driehle** [comment]
Please open an issue at https://github.com/doctrine/doctrine-laminas-hydrator if this is still relevant.
