### ISSUE TITLE
Custom value for ObjectSelect

### ISSUE THREAD

**Issue by codeliner** [doctrine/DoctrineModule#410]
Hello,

I've struggled with the ObjectSelect functionality cause I didn't read the docs carefully :-). My problem was that I needed to use a name of an entity as
label of the select options but the identifier of a foreign entity as value. I thought I can use a method as property provider to achieve this. Something like this:

``` php
array(
    'type' => 'DoctrineModule\Form\Element\ObjectSelect',
    'name' => 'name',
    'options' => array(
        'object_manager' => $this->getObjectManager(),
        'target_class'   => 'Module\Entity\Task',
        'property'       => 'getForeignEntityId', //Thought I can use property to define value
        'is_method'      => true,
        'label_generator' => function($taskEntity) {
            return $taskEntity->getName();
        }
        //...
    ),
)
```

But it didn't work so I read the docs again and noticed that the "property" config also defines the option labels. It is just another way to do so. Now I was searching for another possibility and recognized that there is no functionality available. The Proxy always provides the identifier of the connected entity as value for the select options.
In most cases this would be the expected behavior but in my case it is not. I've extended both classes (ObjectSelect and Proxy) to add the missing feature.
Does it make sense to provide a pull request with my changes? I do not like the naming conflicts, see my current ObjectSelect config:

``` php
array(
    'type' => 'DoctrineModule\Form\Element\ObjectSelect',
    'name' => 'name',
    'options' => array(
        'object_manager'  => $this->getObjectManager(),
        'target_class'    => 'Module\Entity\Task',
        'property'        => 'name', //Use name as label
        'is_method'       => false,
        'value'           => 'getForeignEntityId', //use foreign entity id as value
        'value_is_method' => true, //Use value definition as method to retrieve foreign key
        //...
    ),
)
```

What do you think about the feature? Is it useful enough? Suggestions for better config key naming?

**Comment by chateaux** [comment]
Very useful, saved me the trouble of writing this. :)

**Comment by TomHAnderson** [comment]
@codeliner Can you add anything to this?  If it's an issue you'd like to see resolved can you provide a unit test or other PR-able code?

**Comment by codeliner** [comment]
wow, that's an old issue. I think it can be closed. I don't even remember the problem :D

**Comment by TomHAnderson** [comment]
This issue was closed and the reason is in the discussion.  If you have a new issue to open then do so.
