### ISSUE TITLE
Usage of ZendStorageCacheFactory

### ISSUE THREAD

**Issue by j-schumann** [doctrine/DoctrineModule#413]
Hello,
I try to use a cache object provided by ZF as Doctrine cache.
The web says:

```
'services' => array(
    'factories' => array(
        'doctrine.cache.zend_storage' => function($services) {
            return new ZendStorageCache($services->get('defaultCache'));
        },
    ),
),
```

But what for is the DoctrineModule\Service\ZendStorageCacheFactory? I could not find any documentation about how to use it.
I can not use it as

```
    'service_manager' => array(
        'factories' => array(
            'doctrine.cache.zend_storage' => 'DoctrineModule\Service\ZendStorageCacheFactory'
        ),
    ),
```

as is requires a name as constructor parameter which isn't supported by ZF.

I can not use it as 

```
'doctrine_factories' => array(
    'cache' => 'DoctrineModule\Service\ZendStorageCacheFactory',
)
```

(I tried it because it inherits from the default DoctrineModule\Service\CacheFactory) but this throws an exception when there are still other caches, e.g. 'array', configured because they have no 'instance' option.

Which are the use cases for this class? How do I cofigure my module to use it? 

Why isn't zendstorage in the default config[doctrine][cache] provided by the module and supported by the CacheFactory? Probably because it's API is not consistent with the other cache types requiring an additional instance like

```
        if ($cache instanceof MemcacheCache) {
            $cache->setMemcache($instance);
```

Thanks in advance for your help,
JS

**Comment by gianarb** [comment]
HI! @j-schumann have you solve this problem?
Thanks!

**Comment by j-schumann** [comment]
Hi @gianarb, I just used the closure as factory:

```
    public function getServiceConfig()
    {
        return array(
            'factories' => array(
                'doctrine.cache.zend_storage' => function($sm) {
                    return new \DoctrineModule\Cache\ZendStorageCache(
                            $sm->get('defaultCache'));
                },
            ),
        );
    }
```
This is in my module class. 

I have heard nothing back from @Ocramius, the ZendStorageCacheFactory is still in the master (https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Service/ZendStorageCacheFactory.php) and shows no hint of deprecation.

**Comment by TomHAnderson** [comment]
You've created an instance where you didn't need the factory.  It may have been easier to use it; I can't say.  

Closing this ticket.

**Comment by j-schumann** [comment]
@TomHAnderson Thanks, I know, i did this because I could **not** use the factory (see first post) as it is not compatible with other services/the common factory API. 

The remaining question is: Why is the factory class still in the repository as @Ocramius  said it's deprecated and as it's not usable in its current state? It should be marked as deprecated and removed with the next major version.

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/DoctrineModule/pull/628
