### ISSUE TITLE
FormElements and Array hydration instead of object

### ISSUE THREAD

**Issue by webdevilopers** [doctrine/DoctrineModule#415]
Sometimes forms can get big and include a lot of Doctrine **FormElements**.
I've been wondering about performance issues since the object hydration is always used.

Isn't there a lot overhead? (Unfortunately I can't mark this issue as **Question**)

This was one of my original elements:

``` php
        $this->add(array(
            'type' => 'DoctrineModule\Form\Element\ObjectSelect',
            'name' => 'branch',
            'attributes' => array(
                'class' => 'form-control',
                'tabindex' => 5,
            ),
            'options' => array(
                'target_class'   => 'Application\Entity\Branch',
                'property'       => 'name',
                'display_empty_item' => true,
                'empty_item_label'   => '---',
                'label_generator' => function($branch) {
                    return $branch->getCompany()->getName() . ', ' . $branch->getName();
                },
                'is_method'      => true,
                'find_method'    => array(
                    'name'   => 'findBy',
                    'params' => array(
                        'criteria' => array('company' => 1),
                    ),
                ),
            ),
        ));
```

Now I tried to use Array hydration changing my form element as follows:

``` php
        $this->add(array(
            'type' => 'DoctrineModule\Form\Element\ObjectSelect',
            'name' => 'branch',
            'attributes' => array(
                'class' => 'form-control',
                'tabindex' => 5,
            ),
            'options' => array(
                'target_class'   => 'Application\Entity\Branch',
                'property'       => 'name',
                'display_empty_item' => true,
                'empty_item_label'   => '---',
                'label_generator' => function($branch) {
                    return $branch['company']['name'] . ', ' . $branch['name'];
                },
                'is_method'      => true,
                'find_method'    => array(
                    'name'   => 'findBranchesByCompany',
                ),
            ),
        ));
```

And adding my custom repository method:

``` php
    public function findBranchesByCompany()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select(array('b', 'c'))
            ->from('Application\Entity\Branch', 'b')
            ->join('b.company', 'c')
            ->where('b.compartment = 1')
            ->orderBy('c.name')
            ->addOrderBy('b.name')
        ;

        #return $qb->getQuery()->getResult();
        return $qb->getQuery()->getArrayResult(); // Testing Doctrine FormElement hydration
    }
```

The `label_generator` still works fine and the `select` is still populated correctely.
The only message I get per item is:
**Warning: ReflectionProperty::getValue() expects parameter 1 to be object, array given in /home/.../vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php on line 697**

Is there a way to switch to `ArrayHydration` and does it actually make sense?

BTW: I recognized that with the current version of **Doctrine** setting the `object_manager` on the **formElement** is obsolete when the **Fieldset** implements the `ObjectManagerAwareInterface`?

**Comment by davidmintz** [comment]
and, that being the case, if you have caching enabled (as you surely will in production), then it should not make a consequential difference UNLESS your array of options is large -- but if it's really large then it's time to look for another UI approach, e.g., autocompletion. true?

**Comment by webdevilopers** [comment]
Sure! Since we started using DTOs fir Commands as data_class we only have primitive types and objectIds - no more objects or persistence related implementations like repositories in our forms at all.
