### ISSUE TITLE
Hydrator.md  -- a complete example using Zend\Form

### ISSUE THREAD

**Issue by paguemaou** [doctrine/DoctrineModule#422]
I'm learning ZF2 / Doctrine.

Could you provide the create.phtml  /  edit.phtml views for the "complete example using Zend\Form" ? 

In fact, I try in create.phtml view :

<?php 
$form->prepare();
echo $this->form()->openTag($form);
.....................................................................
$blogpost = $this->form->get('BlogPost');    => Zend\Form\Exception\InvalidElementException
 ................................................................... => No element by the name of [BlogPost] found in form
echo $this->formRow($blogpost->get('id'));
echo $this->form()->closeTag();
?>

Thanks in advance.

**Comment by gianarb** [comment]
I close this issue
Thanks!
