### ISSUE TITLE
Hydrator Strategy->setCollectionName() is called multiple times on one instance

### ISSUE THREAD

**Issue by intellix** [doctrine/DoctrineModule#430]
Was attempting to create my own hydrator that extracts Json but Hydrates with AllowRemoveByValue. Just copied the code into my custom hydrator.

Was getting the error: `Found entity of type Meep\V1\Entity\Market on association Meep\V1\Entity\Property#features, but expecting Meep\V1\Entity\Feature`

After some xdebugging, I've found that each Strategy invokable is created once, stored in the ServiceManager and has the CollectionName set on the same instance multiple times before hydrating.

`DoctrineObject.php` calls `prepareStrategies()` which loops through my strategies and calls `$strategy->setCollectionName($association)->setClassMetadata($this->metadata);`.

1) It runs through, sets `$collectionName` to `markets`, 
2) Runs again, against the same instance and sets `$collectionName` to `features`

This isn't a problem if you don't specify a strategy on a relation, because it sees there's no strategy defined and creates new instances of `AllowRemoveByValue` or `AllowRemoveByReference`

My hydrator configuration:

``` php
'Meep\\V1\\Entity\\PropertyHydrator' => array(
    'entity_class' => 'Meep\\V1\\Entity\\Property',
    'object_manager' => 'doctrine.entitymanager.orm_default',
    'by_value' => true,
    'use_generated_hydrator' => true,
    'strategies' => array(
        'markets' => 'AllowRemoveJsonExtract',
        'features' => 'AllowRemoveJsonExtract',
    ),
),
```

For anyone looking for a quickfix:

``` php
return array(
    'service_manager' => array(
        'abstract_factories' => array(
            'ZF\\Apigility\\Doctrine\\Server\\Resource\\DoctrineResourceFactory' => 'ZF\\Apigility\\Doctrine\\Server\\Resource\\DoctrineResourceFactory',
        ),
        'invokables' => array(
            'AllowRemoveJsonExtract' => 'Flatscanner\\V1\\Hydrator\\Strategy\\AllowRemoveJsonExtract',
            'AllowRemoveJsonExtract2' => 'Flatscanner\\V1\\Hydrator\\Strategy\\AllowRemoveJsonExtract',
        ),
    ),
    'doctrine-hydrator' => array(
        'Meep\\V1\\Entity\\PropertyHydrator' => array(
            'entity_class' => 'Meep\\V1\\Entity\\Property',
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'by_value' => true,
            'use_generated_hydrator' => true,
            'strategies' => array(
                'markets' => 'AllowRemoveJsonExtract',
                'features' => 'AllowRemoveJsonExtract2',
            ),
        ),
    ),
);
```

**Comment by driehle** [comment]
Please open an issue at https://github.com/doctrine/doctrine-laminas-hydrator if this is still relevant.
