### ISSUE TITLE
Composite ID's with Unique Validator?

### ISSUE THREAD

**Issue by AydinHassan** [doctrine/DoctrineModule#433]
I have an entity which has a primary key of a `User` object and a date, eg:

``` php
/**
 *
 * @ORM\Entity
 * @ORM\Table(name="booking")
 */
class Booking 
{

    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="JhUser\Entity\User")
     */
    protected $user = null;

    /**
     * @ORM\Id
     * @ORM\Column(type="date", name="date", nullable=false)
     */
    protected $date;

    public function setUser(UserInterface $user)
    {
        $this->user = $user;
        return $this;
    }
    public function getUser()
    {
        return $this->user;
    }

    public function setDate(DateTime $date)
    {
        $this->date = $date;
        return $this;
    }

    public function getDate()
    {
        return $this->date;
    }
}
```

How can I make sure that the user/date combination is unique? Each user can only have one booking per day.

I have the following input filter specification:

``` php
class BookingInputFilter extends InputFilter
{

    /**
     * @param ValidatorInterface $uniqueBookingValidator
     */
    public function __construct(ValidatorInterface $uniqueBookingValidator) {

        $this->add(
            [
                'name'      => 'date',
                'required'  => true,
                'validators' => [
                    [
                        'name'      => 'Date',
                        'options'   => [
                            'format' => 'd-m-Y',
                        ],
                    ],
                    $uniqueBookingValidator,
                ],
            ]
        );
    }
}
```

Unique Validator:

``` php
 $uniqueValidator = new UniqueObject(array(
        'object_manager'    => $objectManager,
        'object_repository'  => $bookingRepository,
        'fields' => array(
            'date',
            'user',
        )
    ));
```

It seems that the Unique Validator will only search for a record in the repository using the `date` value and will not use the `user` value from the context. Is this correct or am I missing something? 
Should maybe `cleanSearchValue` accept the context instead of the `$value`

Willing to PR if necessary. Maybe I am trying to achieve this the wrong way?

**Comment by j-schumann** [comment]
Having the same problem using ZF2 Forms.
My Entity uses a composite key of a reference and a string field, both are separate form elements (DoctrineModule\Form\Element\ObjectSelect and Zend\Form\Element\Text), the uniqueObject validator is added to the text field. When calling isValid() all necessary data is present in $context but not used by cleanSearchValue() to construct the identifier array to use for findOneBy().

I would opt for cleanSearchValue() to check $value for the required fields and fall back to $context if the no value was found.
