### ISSUE TITLE
Primary Key as Entity in UniqueValidator

### ISSUE THREAD

**Issue by AydinHassan** [doctrine/DoctrineModule#434]
My entity has a primary key of user + date. The user is another entity:

``` php
/**
 *
 * @ORM\Entity
 * @ORM\Table(name="booking")
 */
class Booking 
{

    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="JhUser\Entity\User")
     */
    protected $user = null;

    /**
     * @ORM\Id
     * @ORM\Column(type="date", name="date", nullable=false)
     */
    protected $date;

    public function setUser(UserInterface $user)
    {
        $this->user = $user;
        return $this;
    }
    public function getUser()
    {
        return $this->user;
    }

    public function setDate(DateTime $date)
    {
        $this->date = $date;
        return $this;
    }

    public function getDate()
    {
        return $this->date;
    }
}
```

If a match is found then the call to [`getFoundIdentifiers`](https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Validator/UniqueObject.php#L115) returns an array with a `DateTime` instance. (This has a `__toString()` method) and an instance of `JhUser\Entity\User`. 

Obviously the [`array_diff_assoc`](https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Validator/UniqueObject.php#L117) fails because of the `JhUser\Entity\User` object. With the message: `Catchable fatal error: Object of class JhUser\Entity\User could not be converted to string`

What needs to be done here? Surely I don't actually need to load the `JhUser\Entity\User` instance, all I need to compare is the id's? Is there a way to just load the base entity and not its associations? 

``` php
\\\$expectedIdentifiers
array (
  'user' => 18,
  'date' => 
  JhFlexiTime\DateTime\DateTime::__set_state(array(
     'date' => '2014-09-04 00:00:00',
     'timezone_type' => 3,
     'timezone' => 'Europe/London',
  )),
)
```

``` php
\\$foundIdentifiers
array (
  'user' => JhUser\Entity\User:: ......,
  'date' => 
  JhFlexiTime\DateTime\DateTime::__set_state(array(
     'date' => '2014-09-04 00:00:00',
     'timezone_type' => 3,
     'timezone' => 'Europe/London',
  )),
)

```

**Comment by TomHAnderson** [comment]
@AydinHassan if it works for you then the approach is ok.  Using compound primary keys in Doctrine is limited to many to many relationships and not really supported.  Best to have a unique index on the two columns which make up your primary key and use a standard id primary key column.
