### ISSUE TITLE
Hydration - nested entity with composite keys

### ISSUE THREAD

**Issue by intellix** [doctrine/DoctrineModule#441]
I'm having an issue with hydrating a ManyToMany within DoctrineModule that was converted to a OneToMany/ManyToOne for storing additional data within my association. Here are what originally worked:

``` php
class Property
{
  /** @ORM\ManyToMany(targetEntity="Market") */
  private $markets;
}

class Market {}
```

Within DoctrineModule, hydrating an entity along with it's ManyToMany assocation in one go is as easy as passing the following data:

``` js
var property = {
  name: "Blah blah",
  markets: [
    {
      id: 1
    },
    {
      id: 2
    }
  ]
};
```

Which will create a Property and PropertyMarket assocation using the Market ID passed in. Doctrine knows that it requires the Property so inserts it first, then using it's new ID, creates the association row as well. Now I need to hold some additional data within the Assocation table, like currency for instance, I created the actual class and fixed the relationships like so:

``` php
class Property
{
  /** @ORM\OneToMany(targetEntity="Market", mappedBy="property") */
  private $propertyMarkets;
}

class PropertyMarket
{
  /**
   * @ORM\Id
   * @ORM\ManyToOne(targetEntity="Property", inversedBy="markets")
   * @ORM\JoinColumns({
   *   @ORM\JoinColumn(name="property_id", referencedColumnName="id", nullable=false)
   * })
   */
  private $property;

  /**
   * @ORM\Id
   * @ORM\ManyToOne(targetEntity="Market", inversedBy="markets")
   * @ORM\JoinColumns({
   *   @ORM\JoinColumn(name="market_id", referencedColumnName="id", nullable=false)
   * })
   */
  private $market;
}

class Market{}
```

Now with the above, I'm having an issue with hydrating and am getting the following errors with these attempts:

``` js
// missingIdentifierField "property"
var property = {
  "name": "Blah blah",
  "propertyMarkets": [
    {
      "market": {
        "id": 1
      },
      "currency": "EUR"
    }
  ]
};

// missingIdentifierField "property"
var property = {
  "name": "Blah blah",
  "propertyMarkets": [
    {
      "market": {
        "id": 1
      },
      "currency": "EUR"
    }
  ]
};

// missingIdentifierField "property"
var property = {
  "name": "Blah blah",
  "propertyMarkets": [
    {
      "market": {
        "id": 1
      },
      "currency": "EUR"
    }
  ]
};

// Unrecognised identity field: "currency"
var property = {
  "name": "Blah blah",
  "propertyMarkets": [
    {
      "market": {
        "id": 1
      },
      "property": {
        "id": null
      },
      "currency": "EUR"
    }
  ]
};

// No Errors, but also no assocation created.
var property = {
  "name": "Blah blah",
  "propertyMarkets": [
    {
      "market": {
        "id": 1
      },
      "property": {
        "id": null
      }
    }
  ]
};
```

After some investigation into what's happening. I can see that:
- DoctrineObject during toMany() is sending the whole object to ->find() which complains about `currency` being an unrecognised ID field.
- Upon fixing that, something like the following is needed to create the new entity: https://github.com/doctrine/DoctrineModule/issues/439
- Doctrine can automatically persist the new ManyToMany by creating the parent entity first and then using the generated ID to insert the association. Trying this on a ManyToOne/OneToMany complains about: `Entity\PropertyMarket is missing an assigned ID for field  'property'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly."`

So I suppose to summarise: It's not possible to Hydrate a `ManyToMany` with additional fields.

**Comment by edigu** [comment]
Is this issue related with https://github.com/doctrine/DoctrineModule/issues/393 ?

**Comment by driehle** [comment]
Please open an issue at https://github.com/doctrine/doctrine-laminas-hydrator if this is still relevant.
