### ISSUE TITLE
Hydrator null values for uuid type

### ISSUE THREAD

**Issue by Moring** [doctrine/DoctrineModule#443]
As Ocramius points out, ZF2 + Doctrine2 + DoctrineObject Hydrator there are cases where a '' string is a valid value.

So '' is sent when the DoctrineModule\Form\Element\ObjectSelect has an 'empty_option' set.

In ZF2 forms, this can create issues when using ObjectSelect and the like.

I had opened it as a Hydrator issue for UUID types, as '' is not a valid value for that type.  Fortunately there is a work around, using a  Zend\Filter\Null. TIMTOWTDI

So I am changing this to a "please note in the docs suggestion"

**Comment by gianarb** [comment]
Hi @Moring can you send a PR with this update?
Thanks

**Comment by TomHAnderson** [comment]
Closing for lack of follow-up.
