### ISSUE TITLE
ZF2 + Doctrine Pagination OrderBy? 

### ISSUE THREAD

**Issue by Jarker** [doctrine/DoctrineModule#445]
Hey, just having a little trouble with ordering my results using Doctrine and Zend? I want to be able to order the results by desc but it keeps throwing an error.

My code:
$em = $this->getServiceLocator()->get('Doctrine\ORM\EntityManager');
        $getRepo = $em->getRepository('\Application\Entity\Repo')->findBy(array(), array('id' => 'DESC'));
        $forPaginator = new SelectableAdapter($getRepo);

Error:
PHP Catchable fatal error:  Argument 1 passed to DoctrineModule\Paginator\Adapter\Selectable::__construct() must implement interface Doctrine\Common\Collections\Selectable, array given, called in /var/www/html/project/module/Application/src/Application/Controller/getRepoController.php on line 40 and defined in /var/www/html/project/vendor/doctrine/doctrine-module/src/DoctrineModule/Paginator/Adapter/Selectable.php on line 53.

**Comment by gluque** [comment]
What was the solution? I have the same issue!
