### ISSUE TITLE
non-existing entity association from array [question]

### ISSUE THREAD

**Issue by kukoman** [doctrine/DoctrineModule#448]
Hi;

is there a way to hydrate and persist new entity from an array? instead of doing the following:

``` php
        $blogPost = new Entity\BlogPost();
        $tag1 = new Entity\Tag();
        $tag1->setName('foo');

        $data = array(
            'title' => 'The best blog post in the world !',
            'tags'  => [$tag1, ...]
        );
```

to do something like:

``` php
        $data = array(
            'title' => 'The best blog post in the world !',
            'tags'  => [ 
                ['name' => 'foo'], // should create new tags
                ['name' => 'bar'], 
            ],
        );

        $this->em->persist($blogPost);
        $this->em->flush($blogPost);
```

thanks for help

**Comment by gianarb** [comment]
Hi! Have you found a solution? Thanks

**Comment by kukoman** [comment]
Hi there,
nope, I haven't :-1:

**Comment by gianarb** [comment]
Have you tried `hydrator\ObjectDoctrine`?
I don't know if it's a possibile solution :)

**Comment by sopta** [comment]
Hi @kukoman,

I've run into this problem recently and I found out a solution. Either you can change Hydrator's code directly or extends the class ```DoctrineModule\Stdlib\Hydrator\DoctrineObject```. I think extending the class is a better solution. And now you have to change the ```foreach``` statement in the toMany method.

```php
foreach ($values as $value) {
	if (is_array($value)) {
		$identifier = isset($value['id']) ? $value['id'] : NULL;
		$identifier = is_string($identifier) ? (int) $identifier : $identifier;

		$targetObject = $this->find($identifier, $target) ?: new $target;
		$targetObject = $this->hydrate($value, $targetObject);
		$collection[] = $targetObject;

	} else {
		$collection[] = $this->find($value, $target);
	}
}
```

Now, you're able to use your code with the nested array. Also, you can use a 'zero' identifiers thanks to 
```php 
$identifier = isset($value['id']) ? $value['id'] : NULL;
$identifier = is_string($identifier) ? (int) $identifier : $identifier; 
```

I hope that my code is helpful. I wanna create pull request to fix this bug (feature).

**Comment by sopta** [comment]
Just one update. Instead of writing the ```$identifier``` variables you should write this:
```php 
$identifiers = array_intersect_key(
	$value,
	array_flip($metadata->getIdentifier())
);
```

It's more readable and this mechanism of getting identifiers is used in the ```\DoctrineModule\Stdlib\Hydrator\DoctrineObject::toOne``` method as well. I hope that's all. I'll see how it works in the real world.

**Comment by mdjaman** [comment]
Got a warning with \DoctrineModule\Stdlib\Hydrator\DoctrineObject we should add a check since `array_flip` can emit a warning

> array_flip(): Can only flip STRING and INTEGER values! in /Users/marceldjaman/Projects/stelab/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php on line 387
