### ISSUE TITLE
Hydrators with 'empty' identifiers will not be loaded

### ISSUE THREAD

**Issue by kokx** [doctrine/DoctrineModule#456]
I have a identifier, in which it is entirely valid (and possible) for an identifier to have the value '0'. When it is not '0', the DoctrineObject hydrator works as it should, and it will fetch the corresponding object from storage.

However, when the identifier is '0', it will not fetch the existing object from storage. I have traced this back to the following line: https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L357

That line checks if the identifier is empty, and PHP evaluates `empty('0')` as `true`. Hence, it will not continue to try to fetch the object from storage. I think that changing the check to something like `strlen($data[$identifierName]) == 0` would be a better option.

**Comment by gianarb** [comment]
Thanks 96335d7
