### ISSUE TITLE
Command line interface no longer works.

### ISSUE THREAD

**Issue by jarrettj** [doctrine/DoctrineModule#470]
Using doctrine-orm 2.5 and docrine-orm-module master. Executing:

```
php vendor/bin/doctrine-module
```

Gives:

```
PHP Warning:  array_map(): An error occurred while invoking the map callback in /var/www/litigation/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php on line 136
....
Zend\ServiceManager\Exception\ServiceNotCreatedException: An exception was raised while creating "Router"; no instance returned in /var/www/litigation/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 930
```

There are lots more errors. Just listed the first and last one.

**Comment by Ocramius** [comment]
Ping @bakura10 - no bandwidth to check it right now

**Comment by Ocramius** [comment]
> PHP Warning:  array_map(): An error occurred while invoking the map callback in /var/www/litigation/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php on line 136

Which exception? 

According to https://github.com/doctrine/DoctrineORMModule/blob/61827e4ed682727ac83de88c3cdb8075e71a53c2/src/DoctrineORMModule/Module.php#L136, this is just a list of commands pulled from the locator.

**Comment by bakura10** [comment]
I have tried this,and I don't have any issue. Still the very famous "Router" exception (hey @Dasprid, your component always show the most cryptic errors ever :p). Most of the time this is due to an error elsewhere in your code. The problem with this "Router" exception is "where".

Do you have Doctrine Migrations installed ? If so, please try to upgrade it to dev-master instead of using the latest tag (1.0.0-alpha).

**Comment by Ocramius** [comment]
The exception is not cryptic at all, but we miss:

 - stack traces
 - previous exceptions

This is a typical "router could not be instantiated" issue, nothing fancy about it.

**Comment by bakura10** [comment]
Those exceptions are cryptic. I often encounter them, and they are not meaningful at all. Typically something like "Router could not be instantiated, "" could not be found"

**Comment by jarrettj** [comment]
Sorry about delay! Scrum standup went on way too long! @bakura10 changing doctrine migrations to dev-master did the trick. Thanks.
