### ISSUE TITLE
Many to many relationships are not cached.

### ISSUE THREAD

**Issue by jarrettj** [doctrine/DoctrineModule#472]
Second level cache does not cache many to many relationships. I've noticed that there's no example with a many to many relationship. Is this a bug or not supported?

**Comment by Ocramius** [comment]
@jarrettj are you sure that this is a DoctrineModule issue? Did you look at the ORM test suite?

**Comment by jarrettj** [comment]
Thanks. I will raise this in the DoctrineOrmModule then. My bad. :) My workaround is to clear the cache when dealing the many to many relationships. Which is not ideal, but works for now.

**Comment by Ocramius** [comment]
@jarrettj no, I'm wondering if it's a "module" question at all. Isn't this ORM specific?

**Comment by jarrettj** [comment]
Oh. I assumed it would either be doctrine-orm-module or orm issue. That is where the 2nd level cache lives. I think :)
