### ISSUE TITLE
Catchable fatal error: Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by prolic** [doctrine/DoctrineModule#473]
When I persist a composed entity (Company with related users collection) I receive this error:

```
Catchable fatal error: Object of class DateTime could not be converted to string in ...vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2945

15	1.3415	23539680	Zend\Form\Form->isValid( )	../Registration.php:63
16	1.3454	23645096	Zend\Form\Form->bindValues( )	../Form.php:516
17	1.3474	23655352	Zend\Form\Fieldset->bindValues( )	../Form.php:366
18	1.3486	23663560	DoctrineModule\Stdlib\Hydrator\DoctrineObject->hydrate( )	../Fieldset.php:597
19	1.3487	23663872	DoctrineModule\Stdlib\Hydrator\DoctrineObject->hydrateByValue( )	../DoctrineObject.php:106
20	1.3509	23701520	DoctrineModule\Stdlib\Hydrator\DoctrineObject->toMany( )	../DoctrineObject.php:276
21	1.3546	23711640	DoctrineModule\Stdlib\Hydrator\DoctrineObject->find( )	../DoctrineObject.php:421
22	1.3546	23711640	Doctrine\ORM\EntityManager->find( )	../DoctrineObject.php:493
23	1.3546	23712344	Doctrine\ORM\UnitOfWork->tryGetById( )	../EntityManager.php:417
24	1.3546	23712784	implode ( )	../UnitOfWork.php:2945
```

**Comment by Ocramius** [comment]
Check http://stackoverflow.com/questions/15080573/doctrine-2-orm-datetime-field-in-identifier

**Comment by prolic** [comment]
DateTime is _not_ an identifier. I have simple DB-generated primary keys (integers).

**Comment by Ocramius** [comment]
@prolic what's the state of the entity at stack level 21 in your trace? What is DoctrineObject trying to do?

**Comment by prolic** [comment]
I have a very big complex entities, so posting them here would perhabs not be that helpful.

I have a "Company" entity and a "Company Form". The company is related to one or many contacts.
Part of the company form is, that you can also change your user details.

So I have a company entity, that I want to hydrate after $form->isValid().

Checks here: L275:

    elseif ($metadata->isCollectionValuedAssociation($field)) {
        $this->toMany($object, $field, $target, $value);
    }

and $field equals 'contacts'

So toMany() is called next. And in the "values" I have a datetime object.

Sorry, when it doesn't help I will prepare a test-case tomorrow.

**Comment by Ocramius** [comment]
The fact that `value` contains a `DateTime` instance is actually the problem IMO. Check where that value comes from, I'd say.

**Comment by prolic** [comment]
I have a company with a one-to-many relationship (contacts) with a user entity.
A user is always associated with a company. The problem seems to arise from the following situation:

i have a company form and i integrate the currently logged in user data as the contacts subform, so the user can edit himself and the company details on the same page. Hydration however is not possible because for the second related entity it loops through all values and if it's an object, it will try to fetch it from the object manager.

Current workaround: Have to distinct forms, company & user. Show them both on the website but hydrate and persist them individually, not as a single form.

Does anyone have a better solution?

**Comment by prolic** [comment]
Problem comes from using a Form\ComposedObject instead of a Form\Collection. Solved.
