### ISSUE TITLE
How to translate Doctrine Authentication Validator messages

### ISSUE THREAD

**Issue by berturion** [doctrine/DoctrineModule#476]
Hello,
I would like to translate messages set by Doctrine in `DoctrineModule\Authentication\Adapter\ObjectRepository` class but I can't find out how.
I use po/mo files in my module.
Messages are:
'A record with the supplied identity could not be found.'
'Supplied credential is invalid.'
'Authentication successful.'

I noticed that we could use the `Zend\Validator\AbstractValidator` mecanism to translate them. Maybe using the `TranslatorAwareInterface` interface.

Thanks for your help.

**Comment by Estigy** [comment]
Hi, folks.

I just ran into the same issue and would like to +1 for the ```TranslatorAwareInterface``` solution.

Have a look at how the ```Zend\Validator\AbstractValidator``` does it with the translateMessage() method.

Greets, Estigy
