### ISSUE TITLE
Aliasing not possible with default name 'orm_default'

### ISSUE THREAD

**Issue by stefankleff** [doctrine/DoctrineModule#482]
Adding an alias to the ServiceManager does not work if the AbstractDoctrineServiceFactory is used and the service name contains an underscore (like it is in "orm_default").
```
alias => [
"EntityManager"  => "doctrine.entitymanager.orm_default"
]
```
Reason:
When an alias is added in the ServiceManager the target of the alias is stored in canonicalized format. Therefore all underscores (and various other chars) are removed. Then the AbstractDoctrineServiceFactory is not able to find the corresponding config key anymore and the service could not be created.

Possible Solutions:
1. Rename "orm_default" to "default" (major BC break)
2. Remove the underscore from ServiceManager::$canonicalNamesReplacements (just a workaround with unknown side effects)
3. Somehow use the same canonicalize function to check the config keys (slow)

**Comment by Ocramius** [comment]
Known issue: we currently solve it via an [`EntityManagerAliasCompatFactory`](https://github.com/doctrine/DoctrineORMModule/blob/e81f86a96663d3117a894f427a72ce853b9e79fa/src/DoctrineORMModule/Service/EntityManagerAliasCompatFactory.php)

This is a "can't fix" that is part of ZF3's timeline.
