### ISSUE TITLE
How to disable caching in development environment

### ISSUE THREAD

**Issue by chateaux** [doctrine/DoctrineModule#494]
ZF2/Doctrine

I noticed files are stored in the data/DoctrineModule/cache and sometimes I have to delete these files when I make updates to my entities or change DB structures etc.

I did not consciously  enable this and have been trying to figure out hot to switch it on and off with not much luck.

Clearly this is a config issue, kindly point me in the direction of the documentation relating to this as it is something I would like to use in production.

For brevity I have posted a detailed outline here on SO: http://stackoverflow.com/questions/29720621/zf2-doctrine-orm-how-to-turn-off-the-doctrinemodule-cache

Many thanks,

**Comment by mpalourdio** [comment]
Please check if 'config_cache_enabled' option.

**Comment by chateaux** [comment]
I have the following set in my development config:

<?php
return array(
    'modules' => array(
        'ZF\Apigility\Admin',
        'ZF\Configuration',
    ),
    'module_listener_options' => array(
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}-development.php'),
        'config_cache_enabled'     => false,
        'module_map_cache_enabled' => false,
    ),
);

This of course does not disable teh DoctrineModule cache

**Comment by gianarb** [comment]
Hi @chateaux I don't know if you can disable caching but maybe you can use `array_adapter` this adapter not persist files in your SO

[Doc](http://doctrine-orm.readthedocs.org/en/latest/reference/caching.html#caching)
