### ISSUE TITLE
Validators are founded on broken approach to option validation

### ISSUE THREAD

**Issue by Bilge** [doctrine/DoctrineModule#499]
All the validators shipped with this module are founded on the broken assumption that it is OK to validate the options at construction time. This is not how Zend validators are designed to be used. There are [2 ways](https://samsonasik.wordpress.com/2014/02/02/zend-framework-2-utilize-validatormanager-to-work-with-custom-validator-in-zendform/) to build a validation chain &ndash; one of which involves passing configuration to a factory. It is impossible to create any of the current validators using the factory.

The correct approach is to add mutator methods for each option so that the underlying call to `setOptions` in `AbstractValidator` can do its work. Then, if you want to validate the options passed to the validator, this should be done when and only when `isValid` is called.

Having done all this, validators still cannot be created using configuration since they still require objects passed to them instead of scalar types. This issue is addressed in #500 with an accompanying solution.

**Comment by TomHAnderson** [comment]
A slightly different approach than the one suggested here still gives dynamic options through the factory and though they are passed to the validator at construction of the validator this is not the same as when `__invoke` is called on the factory.

Please see https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Validator/ObjectExistsFactory.php for a working solution.
