### ISSUE TITLE
Validators should implement ObjectManagerAwareInterface

### ISSUE THREAD

**Issue by Bilge** [doctrine/DoctrineModule#500]
The validators claim to require an `object_repository` option. This makes the class very difficult to use because it often involves breaking established patterns to fulfill this requirement. Moreover, it is impossible to create these validators in an [input filter specification](http://framework.zend.com/manual/current/en/modules/zend.input-filter.specs.html) since the service manager is not available in configuration files.

If the validators implemented `ObjectManagerAwareInterface` and an initializer was added to `ValidatorPluginManager` to inject this dependency then it removes the burden from the user to provide this object entirely.

This initializer can be written as follows.

```php
use Doctrine\ORM\EntityManager;
use DoctrineModule\Persistence\ObjectManagerAwareInterface;
use Zend\ServiceManager\InitializerInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use Zend\Validator\ValidatorPluginManager;

class ObjectManagerInitializer implements InitializerInterface
{
    /**
     * Initialize ObjectManagerAwareInterface instances.
     *
     * @param object $instance
     * @param ValidatorPluginManager $serviceLocator
     * @return void
     */
    public function initialize($instance, ServiceLocatorInterface $serviceLocator)
    {
        if ($instance instanceof ObjectManagerAwareInterface) {
            $instance->setObjectManager($serviceLocator->getServiceLocator()->get(EntityManager::class));
        }
    }
}
```

The initializer can be attached to the `ValidatorPluginManager` with the following configuration.

```php
'validators' => [
    'initializers' => [
         ObjectManagerInitializer::class,
    ],
],
```

This approach eliminates passing any objects to the validators in their configuration. `object_repository` and `object_manager` can be replaced with a single key, `repository` which should just be a string describing the class name for the repository. This name can be used to retrieve the repository object from the `ObjectManager` injected by the initializer. 

I happen to know this approach works because I've already implemented it. You're welcome.

**Comment by Ocramius** [comment]
Always been against any `*Aware` interface, to the point that I think that providing the `ObjectManagerAwareInterface` in our codebase was a mistake in first place.

Closing as "won't fix", sorry :-\

**Comment by Bilge** [comment]
Do you care to provide even a single objective justification besides your personal preference?

**Comment by Ocramius** [comment]
@Bilge yeah, sorry, I just thought it was obvious to you, especially since you are a long time user.

In general:

 - initializers are constant overhead
 - initializers assume un-initialized object state, which is a silly idea in first place (constructors ftw, and yes, we have broken code in this module as well)
 - initializers are terrible to debug. They work nicely when they work, but as any magic, when it breaks you are in trouble
 - the `*Aware*` interface exposes public API that shouldn't be exposed in first place (specifically, the getter)
 - initializers are hard to understand for newcomers, and they lead to the typical "why does it not work" problems when the user tries to reuse a class out of the framework context

**Comment by Bilge** [comment]
I'm not going to rebut or argue each point you made but do you have a counter-proposal for simplifying validator configuration?

**Comment by Ocramius** [comment]
@Bilge one possible solution is to provide a factory that replaces or provides a default the `object_manager` option upfront (`array_merge()` style)
