### ISSUE TITLE
UniqueObject validation message contains array instead of scalar

### ISSUE THREAD

**Issue by Bilge** [doctrine/DoctrineModule#501]
When `UniqueObject` fails validation its message shows

> There is already another object matching 'array ( 'foo' => 'bar', )'

instead of 

> There is already another object matching bar

This was [already fixed](https://github.com/doctrine/DoctrineModule/commit/927fd1d0ad7a6d3b407d3360a924c100e618f907#diff-23ce8187a6240f02a6ec84502c38c849) 3 months before 0.8.1 was drafted but somehow the version of the file at 0.8.1 [does not contain this fix](https://github.com/doctrine/DoctrineModule/blob/0.8.1/src/DoctrineModule/Validator/UniqueObject.php#L107-L108) even though _master_ still does. I'd really like to know how a fuck-up of this magnitude could possibly have happened. I'm guessing master was not tagged but a stale branch that was not bought up to parity with master before it was tagged thus losing previously accepted PRs.

**Comment by Ocramius** [comment]
> I'm guessing master was not tagged but a stale branch that was not bought up to parity with master before it was tagged thus losing previously accepted PRs.

Yes, tagging happened on a separate (temporary) branch, since `master` is to be considered `0.9.x`

**Comment by Bilge** [comment]
If 0.8 development is going to take place in parallel to 0.9 for some reason then the commit that fixes this issue should be cherry-picked into the 0.8 branch.

**Comment by TomHAnderson** [comment]
The referenced commit 927fd1d0ad7a6d3b407d3360a924c100e618f907 is in the master branch and is in release 1.2.0
