### ISSUE TITLE
GuardUtils marked as deprecated

### ISSUE THREAD

**Issue by manuakasam** [doctrine/DoctrineModule#503]
https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Form/Element/Proxy.php#L454

GuardUtils is being marked `depricated`. So the functionality behind this should likely be changed to keep upwards compatibility?

**Comment by gianarb** [comment]
Yes in this moment in my opinion we support both implementations

**Comment by TomHAnderson** [comment]
Now uses Zend\Stdlib\Guard

https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Form/Element/Proxy.php#L12
