### ISSUE TITLE
Fixing option_attributes

### ISSUE THREAD

**Issue by manuakasam** [doctrine/DoctrineModule#504]
ping @danizord @gianarb 

So after inspecting the current implementation in `master` regarding the `option_attributes` and basically rewriting them I noticed that they weren't as illogical as I've first throught.

The problem being is that we have basically two kind of attributes:
### Static Attributes

Something like 

``` html
<option class="coolStyledOption" value="1">One</option>
or
<option aria-lang="en" value="one">1</option>
```

In the above example `class` and `aria-lang` are static attributes that are the same for likely all options of this select list.
### Dynamic Attributes

But many attributes are dynamic in the likes of

``` html
<option data-parent="42" value="1">Answer of the Universe</option>
or
<option aria-title="Very descriptive title" value="42">Normal Title</option>
```

The problem here is how to properly support them. I feel that we definitely should support both of them and I basically have two ideas:

``` php
'options' => [
    'option_attributes_static' => [
        'class' => 'funnyClass' // class="funnyClass"
    ],
    'option_attributes_dynamic' => [
        'data-foo' => 'foo' //call getFoo on object as value
    ]
]
```

vs.

``` php

'options' => [
    'option_attributes' => [
        'static' => [
            'class' => 'funnyClass' // class="funnyClass"
        ],
        'dynamic' => [
            'data-foo' => 'foo' //call getFoo on object as value
        ]
    ]
]
```

For some reason though I don't really like the naming of that so before I start the work on this I'd love to get some feedback on your thoughts.

**Comment by gianarb** [comment]
Thanks @manuakasam for this analysis :) 
In my opinion the second proposal is the best way to implement this feature..
```php
'options' => [
    'option_attributes' => [
        'static' => [
            'class' => 'funnyClass' // class="funnyClass"
        ],
        'dynamic' => [
            'data-foo' => 'foo' //call getFoo on object as value
        ]
    ]
]
```
I ping @Ocramius to share with us your opinion and implementation's experience :)

**Comment by danizord** [comment]
I'm :+1: for the second one as well.

**Comment by stefanotorresi** [comment]
i'd rather keep just one array, and infer whether it's static or dynamic from its type, i.e. if it's a callable it will be invoked with the entity as a value, otherwise it's a string.

e.g.
```php
'options' => [
    'option_attributes' => [
        'class' => 'funnyClass',
        'data-foo' => function(My\Entity $entity) { return $entity->getFoo(); },
    ],
]
```

my reasoning being mainly:
- the consumption of your entities api is better self-documented.
- the less meta configuration keys, the better.
- you may want to do one-shot custom stuff like concatenating two values just for the option attribute, and this approach prevent coupling the form configuration with the entity.

just my 2c.

**Comment by manuakasam** [comment]
I like the approach from @stefanotorresi the most out of all three currently presented.

I've thought about this but in my weirdness for some reason I've skipped it at first. Probably due to usability reasons. Writing a callable is more difficult than writing a string of a property name. 

Still, I'd vote +1 for the `string|callable` option

**Comment by gianarb** [comment]
oooo! This code is beautiful! :+1:

**Comment by TomHAnderson** [comment]
@stefanotorresi reply here is adequate.
