### ISSUE TITLE
Hydrator Field Naming Flaw

### ISSUE THREAD

**Issue by sebfek** [doctrine/DoctrineModule#506]
I have fields on an entity that are underscored.
The inputs from the inputfilter are underscored too and matches the member variable name of the entity.
I tried by_value with true and false.
The problem is that it not hydrates my_value to my_value - only myvalue to my_value (or myvalue) on the entity.

**Comment by gianarb** [comment]
Hi! Can you paste a lot of code? Thanks

**Comment by TomHAnderson** [comment]
closed; no response.
