### ISSUE TITLE
how logout 

### ISSUE THREAD

**Issue by faghihian71** [doctrine/DoctrineModule#509]
how we can log out ?

**Comment by Ocramius** [comment]
Not an issue of `DoctrineModule`.

**Comment by faghihian71** [comment]
sry it depends to zend and clearIdentity ,and its a question not an issue ,thank you again

**Comment by Ocramius** [comment]
@faghihian71 yes, I closed it because it is indeed not an issue - questions should go to stackoverflow, irc or the mailing list.
