### ISSUE TITLE
Feature: Add possibility to provide repository method to options

### ISSUE THREAD

**Issue by Wilt** [doctrine/DoctrineModule#513]
This should be considered an `enhancement`:
It would be great if the ObjectExists NoObjectExists validator would allow to set a custom repository method to use while validating. This allows user to add additional logic (static) to the fields (dynamic) that are validated.

Right now the `findOneBy` method is by default used to find a match. I could easily imagine an `setRepositoryMethod` method inside the class so that in options the user can provide an options array with the following:

`'repository_method' => 'findOneByMyCustomMethod'`

The `isValid` method would then look like:

```
/**
 * {@inheritDoc}
 */
public function isValid($value)
{
    $value = $this->cleanSearchValue($value);
    if(isset($this->repositoryMethod)){
        $method = $this->repositoryMethod;
    }else{
        $method = 'findOneBy';
    }
    $match = $this->objectRepository->$method($value);

    if (is_object($match)) {
        return true;
    }

    $this->error(self::ERROR_NO_OBJECT_FOUND, $value);

    return false;
}
```

**Comment by Wilt** [comment]
I can make a pull request if there is interest in such a feature

**Comment by gianarb** [comment]
Good IMO.. :) 
can you write a PR with tests and docs improvement?

Thanks a lot!

**Comment by Wilt** [comment]
A pull request can be found here:
https://github.com/doctrine/DoctrineModule/pull/514

**Comment by TomHAnderson** [comment]
See https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Validator/ObjectExistsFactory.php#L39 for a working example of your request.
