### ISSUE TITLE
Symfony\Component\Console\Helper\DialogHelper is deprecated

### ISSUE THREAD

**Issue by MarcFRICOU** [doctrine/DoctrineModule#515]
Whenever we want to use console entry point with doctrine module dependency, we get :
```
PHP Deprecated:  "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5

**Comment by gianarb** [comment]
This problem is fixed into the master

**Comment by MarcFRICOU** [comment]
I can't use master, it's for production purpose.
I do think that I should not include it for console usage. Thanks for pointing this out
