### ISSUE TITLE
test case on php7

### ISSUE THREAD

**Issue by nimasdj** [doctrine/DoctrineModule#518]
Does this module work on php7?
Has been a test case even ran on php7?

**Comment by snapshotpl** [comment]
https://travis-ci.org/doctrine/DoctrineModule :-)

**Comment by nimasdj** [comment]
Thanks. I am not familiar with travis. Does it run test case?

**Comment by manuakasam** [comment]
If you'd click the link you'd see that PHP7 is marked "green" and therefore
passes all tests.

nimasdj <notifications@github.com> schrieb am Mo., 27. Juli 2015 um
16:49 Uhr:

**Comment by nimasdj** [comment]
Thanks.

**Comment by nimasdj** [comment]
What about all components of ZF2? Passed php7 test case? What is its travis link?

**Comment by gianarb** [comment]
https://travis-ci.org/zendframework
