### ISSUE TITLE
Use antother key than "orm_default" for authentication

### ISSUE THREAD

**Issue by ceadreak** [doctrine/DoctrineModule#519]
Hi team, 

Simple question ... In my ZF2 app, I need to use doctrine auth with 2 different entities "Member" and "User".
"Member" will log in on an e-shop module and "User" will log in the back-office.

So, my question is : I want to use the same AuthService for both e-shop and back-office modules.

To achieve that, I would create 2 doctrine auth keys in my Application config module file such as that : 

```
                          'e-shop' =>
                            [
                                'objectManager'      => EntityManager::class,
                                'identityClass'      => Member::class,
                                'identityProperty'   => 'login',
                                'credentialProperty' => 'password',
                            ],
                        'platform' =>
                            [
                                'objectManager'      => EntityManager::class,
                                'identityClass'      => User::class,
                                'identityProperty'   => 'login',
                                'credentialProperty' => 'password',
                            ]
```

Is it possible ??

Thanks,

C.

**Comment by TomHAnderson** [comment]
http://blog.tomhanderson.com/2016/03/zf2-doctrine-configure-second-object.html
