### ISSUE TITLE
DoctrineObject `toOne` Hydration fails if composite keys are passed in different order

### ISSUE THREAD

**Issue by Wilt** [doctrine/DoctrineModule#525]
The `toOne` method supports hydration for associations with composite keys. If the `$value` is an array and corresponds to the array that is returned by the `getIdentifier` method then it will hydrate the object by finding the relating object using the provided keys.

If the keys are provided in `$value` but the order of the keys is different then the order in which the `getIdentifier` method returns the keys, then `toOne` hydration fails. 

For example we have  a `UserPost` that has a composite key that exists out of a `user` and a `post`. 

We provide the data with both the identifier fields but in the order 'post', 'user':

```
$value = array('post' => 22, 'user' => 1);
```

The `getIdentifiers` method returns the keys in a different order:

```
$identifiers = getIdentifier();  // returns array('user', 'post');
```

[Line 382 in the DoctrineObject hydrator does a check for the keys like this:](https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L382):

```
if (is_array($value) && array_keys($value) != $metadata->getIdentifier()) {
```

Which returns false because `array_keys($value)` is not equal to `$metadata->getIdentifier()`.

It would be better if hydration would also work if keys are provided in any other (random) order.

**Comment by TomHAnderson** [comment]
I think this point is valid and I'll include a PR you wish to send in to change the comparator operator for the `$metadata->getIdentifier();`

However this is old and I'll close the issue in about 2 weeks if there is not movement.

**Comment by driehle** [comment]
Please open an issue at https://github.com/doctrine/doctrine-laminas-hydrator if this is still relevant.
