### ISSUE TITLE
Add class/id to select optgroup

### ISSUE THREAD

**Issue by paddle07** [doctrine/DoctrineModule#526]
Hi,

I'm using Form\Element\ObjectSelect and 'optgroup_identifier' to group my list. Is it possible to add an id or class to the optgroup-tag?

Thanks!

**Comment by manuakasam** [comment]
This is currently not supported. I personally considered the use-case for this to be very marginal (read: not justifiable the additional amount of code required). I suggest giving your select list an Id and then style it using `#selectList > optgroup`

**Comment by andrconstruction** [comment]
I use custom find_method, where I join a table to main entity. How can I get a optgroup_identifier from joined table?

**Comment by manuakasam** [comment]
@andrconstruction Please open a separate issue for your question. OffTopic within Issues isn't that great to maintain.

**Comment by paddle07** [comment]
Thanks for the Info. Actually I need for Javascript but found a way to do it.
