### ISSUE TITLE
setter generation mechanism

### ISSUE THREAD

**Issue by inbaz** [doctrine/DoctrineModule#528]
Hi,

would it be nicer to generate the setters in the hydrateByValue method of DoctrineObject with

```
$setter = sprintf('set%s', ucfirst(
    str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
));
```

instead of

```
$setter = 'set' . ucfirst($field);
```

This leads to searching for the method setMy_field when I use my_field in a doctrine entity. It should search for setMyField, I think.

**Comment by TomHAnderson** [comment]
Non-default naming strategies seem to have their share of problems.  For this idea I can't see it going into production.  If you've got another idea you'd like to PR we can assess that.
