### ISSUE TITLE
Controls usable for (emulated) ManyToMany with additional fields

### ISSUE THREAD

**Issue by cbichis** [doctrine/DoctrineModule#530]
Hi,

As far as I tested all controls which are targeted for ManyToMany relations are not working for OneToMany + ManyToOne case...

I mean I see no reason to not have working MultiCheckbox for this particular case of ManyToMany... So even if we have actually 3 entities not 2...

Is true is not possible to populate the extra fields from join table but sometime is more than enough to just populate with values for these 2 foreign keys...

**Comment by TomHAnderson** [comment]
Please give a follow up to this post.  It's not clear to me what you're issue is or what you think may remedy it.

**Comment by TomHAnderson** [comment]
Closing due to no response by submitter.
