### ISSUE TITLE
Nested forms and binding issue

### ISSUE THREAD

**Issue by jbrtrnd** [doctrine/DoctrineModule#531]
I'm facing a really strange bug in **ZF2 (2.4.2)** using Doctrine2, forms and hydration.  

Assuming this one to many model with 3 levels :  
Entity1 -> Entity2 -> Entity3  
(Entity1 has many Entity2, Entity2 has many Entity3).  

```
class Entity1 {
    /**
     * @ORM\OneToMany(targetEntity="Entity2", mappedBy="entity1", orphanRemoval=true, cascade={"persist", "remove", "merge"})
     */
    protected $entities2;    
}

class Entity2 {
    /**
     * @ORM\ManyToOne(targetEntity="Entity1", inversedBy="entities2")
     */
    protected $entity1;
    /**
     * @ORM\OneToMany(targetEntity="Entity3", mappedBy="entity2", orphanRemoval=true, cascade={"persist", "remove", "merge"})
     */
    protected $entities3;    
}

class Entity3 {
    /**
     * @ORM\ManyToOne(targetEntity="Entity2", inversedBy="entities3")
     */
    protected $entity2;  
}
```

I'm using a set of Zend Forms and Fieldset to build a complete editable view of an Entity1 object.  

```
class Entity1Form {
    public function __construct(EntityManager $entityManager) {

        // Some elements ...

        $this->add(array(
            'type' => 'Zend\Form\Element\Collection',
            'name' => 'entities2',
            'options' => array(
                'count' => 0,
                'should_create_template' => true,
                'allow_add' => true,
                'allow_remove' => true,
                'target_element' => new Entity2Fieldset($entityManager)
            )    
        ));

        $this->setHydrator(new DoctrineObject($entityManager))->setObject(new Entity1());
    }
}

class Entity2Fieldset {
    public function __construct(EntityManager $entityManager) {

        // Some elements ...

        $this->add(array(
            'type' => 'Zend\Form\Element\Collection',
            'name' => 'entities3',
            'options' => array(
                'count' => 0,
                'should_create_template' => true,
                'allow_add' => true,
                'allow_remove' => true,
                'target_element' => new Entity3Fieldset($entityManager)
            )    
        ));

        $this->setHydrator(new DoctrineObject($entityManager))->setObject(new Entity2());
    }
}

class Entity3Fieldset {
        public function __construct(EntityManager $entityManager) {

            // Some elements ...

            $this->setHydrator(new DoctrineObject($entityManager))->setObject(new Entity3());
        }
    }
```

The thing really weird is as follows :  

When I'm binding an Entity1 object to my Entity1Form, every values are correctly set in all elements of Entity1Form, Entity2Fieldset and Entity3Fieldset. When I submit the form, the Entity1 object is correctly hydrated and properties values are changed (relations are correctly managed too - add, delete...).  
**BUT**, You may know we can access the binded object of a form or a fieldset by using the `getObject()` function.  
When I'm doing :  

```
....
$entity1Form = new Entity1Form($em);
$entity1Form->bind($entity1);

$entity1Form->getObject(); // Full binded entity1 object containing relations
$entity1Form->get('aProperty')->getValue(); // Good value
foreach($entity1Form->get('entities2') as $entity2Fieldset) {
    $entity2Fieldset->getObject(); // Full binded entity2 object containing relations
    $entity2Fieldset->get('anotherProperty')->getValue(); // Good value
    foreach($entity2Fieldset->get('entities3') as $entity3Fieldset) {
        $entity3Fieldset->getObject(); // WTF ? An empty entity3 object
        $entity3Fieldset->get('againAnotherProperty')->getValue(); // Good value but WTF AGAIN
    }
}
```

I'm wondering why the `$entity3Fieldset->getObject()` returns an empty Entity3 object while its values are correctyle binded to the fieldset element and it's working good for the 2nd lvl (aka Entity2).
I need to use this Entity3 object in my code and it's impossible in this way (which seems to be the most logical and cleanest).  
I'm ruining my head with this problem...

**Comment by bitwombat** [comment]
Wow, this is 2.5 years old.  How did you end up solving this?  Obviously nobody recognized the problem or they would have chimed in.

**Comment by ddelrio1986** [comment]
To make all this stuff work right with collections try adding this to your entities:

![ease____workspace_ease__-_____module_application_src_entity_quizassessment_php__ease_](https://user-images.githubusercontent.com/58251/42384717-bc44bab2-8108-11e8-96c5-e4992681e316.jpg)

Without the reinitialization of the collections in the clone I always get weird behavior like this during hydration. I first found this solution from this article:

http://adam.lundrigan.ca/2014/04/25/doctrine-collections-nested-zf2-fieldset-collections/

**Comment by driehle** [comment]
Since this is related to the hydrator, please open an issue at https://github.com/doctrine/doctrine-laminas-hydrator if this is still relevant.
