### ISSUE TITLE
Authenticating against multiple identity properies?

### ISSUE THREAD

**Issue by chateaux** [doctrine/DoctrineModule#532]
Hi,

Is there a way to authenticate against either an email or a username?

I am setting up an API login method for third parties and some wish to user customers emails and others wish to use a username.

thanks!

**Comment by TomHAnderson** [comment]
You could use the https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Authentication/Adapter/ObjectRepository.php twice, but that's rather inefficient.  Best to create a custom adapter.
