### ISSUE TITLE
Avoid cascade-like behavior in One-To-Many Unidirectional

### ISSUE THREAD

**Issue by jawira** [doctrine/DoctrineModule#536]
I have an issue with the following one-to-many unidirectional relation between `UserSociable` and `Credential` (I have simplified the code a little bit).

`UserSociable` entity is the owner of the relation:

``` php
/**
 * Class UserSociable
 * @ORM\Entity(repositoryClass="Repository\UserSociableRepository")
 * @ORM\Table(name="userSociable")
 * @DiscriminatorEntry(value="userSociable")
 */
class UserSociable 
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="Credential")
     * @ORM\JoinTable (
     *     joinColumns={@ORM\JoinColumn(name="entity_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="credential_id", referencedColumnName="id", unique=true)}
     * )
     */
    private $credentials;
}
```

`Credential` entity is the inverse side:

``` php
/**
 * @ORM\Entity(repositoryClass="Repository\CredentialRepository")
 * @ORM\Table(name="credentials")
 */
class Credential 
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
}
```

These creates three tables in DB:
- userSociable
- credentials
- usersociable_credential

Once the DB is populated, I have the following issue: when I delete a `userSociable`, Doctrine automatically also removes the corresponding rows in the join table `usersociable_credential`.

I was expecting an exception to raise since the PK is referenced as FK in `usersociable_credential` table. This is the expected behavior since I never used an annotation like `onDelete="CASCADE"` in the join column annotation.

The thing is I want to force to delete all the user's `Credentials` before to being able to delete an `UserSociable`.

I have looked at MySQL log file and found the following queries:

```
151106 12:16:24   113 Query START TRANSACTION
          113 Query DELETE FROM usersociable_credential WHERE entity_id = '1'
          113 Query DELETE FROM ku_user WHERE id = '1'
          113 Query commit
          113 Quit  
          112 Quit
```

How can I avoid the query `DELETE FROM usersociable_credential WHERE entity_id = '1'` to be created and executed by Doctrine???

Thanks in advance.

**Comment by jawira** [comment]
Nobody cares?

**Comment by Dimonion** [comment]
lul
