### ISSUE TITLE
(Dis)AllowRemoveByValue betrays convention

### ISSUE THREAD

**Issue by Bilge** [doctrine/DoctrineModule#538]
`AllowRemoveByValue` and `DisallowRemoveByValue` place a requirement upon the object to implement methods for adding and removing collection elements, which is acceptable, however the implementation requirements betray convention as described below.

The convention to which I am referring is well documented in the manual under [8.4. Association Management Methods](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html#association-management-methods). Mutator methods type hint against the type of document they are expecting, i.e. `function addFavorite(Comment $comment)`.

However, the aforementioned strategies betray this convention by trying to pass entire collections as shown in this code fragment.

``` php
$toAdd    = new ArrayCollection(array_udiff($value, $collection, array($this, 'compareObjects')));
$toRemove = new ArrayCollection(array_udiff($collection, $value, array($this, 'compareObjects')));

$this->object->$adder($toAdd);
$this->object->$remover($toRemove);
```

This requires the mutator method to be implemented in a fashion similar to the following.

``` php
public function addTags(Collection $tags)
{
    foreach ($tags as $tag) {
        $tag->setBlogPost($this);
        $this->tags->add($tag);
    }
}
```

This places two unnecessary burdens on the implementation:
1. It must be able to handle collections even though it may have already been designed to handle single objects as per the documentation.
2. Even if the implementer is happy to handle collections we lose the ability to type hint against the document type we accept.

I recommend these strategies should call the implementation once for each member in the collection instead of passing entire collections. Of course, I am mindful that since they have already been published it may be necessary to create alternative implementations, in which case it should be made easy to switch implementation according to preference, or perhaps automatically, through reflection of the method signature.

**Comment by TomHAnderson** [comment]
I'm going to close this because your icon suggests you're not available.  

I hear what you're asking but I need more from you for an implementation.

**Comment by Bilge** [comment]
>your icon suggests you're not available

Uuuuuuuuuuuuuh. You w0t m8?

**Comment by Bilge** [comment]
>your icon suggests you're not available

Uuuuuuuuuuuuuh. You w0t m8? Does this look like a dead profile to you?

![image](https://user-images.githubusercontent.com/470626/38118813-37715066-33b5-11e8-9017-a5529d03f4dc.png)

@Ocramius @alcaeus Is this really the kind of person you want managing your repository?

**Comment by TomHAnderson** [comment]
No, @Bilge; and please excuse me for only considering your icon and not your profile.  

I'm going to create a 2.0 release soon and this issue you last commented on in 2015, as I said, may have merit but I need more information from you.  A unit test which shows expected functionality would be a good first step.

**Comment by Bilge** [comment]
A *unit test* isn't "more information". If you want more information ask what you need to know.

**Comment by TomHAnderson** [comment]
Please ignore any requests I've made of you thus far.

In order to reopen this issue please provide a unit test expressing the functionality you desire.  It would be even more helpful if you submitted a PR with the functionality you wish to see in this module.

**Comment by Bilge** [comment]
No, dude, there's *plenty* of information here to warrant an open issue. Don't hold my well-written issue hostage to incite me to write code for you. You have no business having commit rights to this repository acting this way.
