### ISSUE TITLE
ManagerRegistry support

### ISSUE THREAD

**Issue by MidnightDesign** [doctrine/DoctrineModule#540]
Is there a reason for why there is no `ManagerRegistry` support in this package? Or is it just not implemented yet?

**Comment by Ocramius** [comment]
Support for it is to be avoided, IMO: it's one of those scenarios that
shouldn't have made it into common :-(

**Comment by MidnightDesign** [comment]
Really? Can you elaborate why you think it's a bad thing or point me to a previous descussion about it?

**Comment by TomHAnderson** [comment]
Closed; no response.
