### ISSUE TITLE
ObjectSelect + object as custom identifier is broken

### ISSUE THREAD

**Issue by manuakasam** [doctrine/DoctrineModule#544]
Hey :)

We just ran into an issue. We're using a custom mapping type as identifier using ramsey/uuid-doctrine by @ramsey 

The problem arising with this is that the Proxy behind the form element is now receiving an object as identified by the custom mapping type. However Zend\Form is not able to use Objects as values since internally the value is usually a `string` an `integer` or `boolean`.

I'm thinking that this may be an issue solely for `ObjectSelect` as this one is taking care of all the magic yadda yadda. 

How would we go on fixing this? Personally I think a simple thing like this would work:
https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Form/Element/Proxy.php#L454

Simply adding a scalar type check beforehand.

```
        if (false === is_scalar($value)) {
            // Maybe do a check if __toString() exists and if not exception?
            $value = (string) $value;
        }

        return $value;
```

What do you think? ping @gianarb

**Comment by gianarb** [comment]
Sounds good, in my opinion we can not check if exist __toString method, if php can not cast the value already triggers an explicit error.

**Comment by mpalourdio** [comment]
Can't you just attach a stategy to the form's hydrator ?

**Comment by manuakasam** [comment]
Hmm, this IS a fair point.
I suppose, since that can be done using a HydratorStrategy, that this doesn't need to be inside DoctrineModule. Sadly this makes things very complex on CustomTypes like this :P

thanks for the feedback tho!

**Comment by rieschl** [comment]
Sorry for posting in a closed issue, but will this be fixed sometimes? I think lots of people use uuid nowadays... An alternative would be an option to set a custom source (= method) for the value.
Thanks!

**Comment by maglnet** [comment]
@rieschl perhaps this works for you:
https://gist.github.com/maglnet/be6966e397237b4c38a3729ff4c04403

**Comment by rieschl** [comment]
@maglnet Nice one, thanks!! Works like a charm :smile: 
Although I still think that something like that should be done by `DoctrineObject` itself. Either with a `__toString` check or, even better if I could provide a custom field which should be used as `value` of the `<option>`.

It seems that [there is something to do anyway](https://github.com/doctrine/DoctrineModule/blob/master/src/DoctrineModule/Form/Element/Proxy.php#L445) concerning the identifiers :smile:
