### ISSUE TITLE
Any reason doctrine-module isn't using doctrine/common 2.6?

### ISSUE THREAD

**Issue by mattgrosse** [doctrine/DoctrineModule#545]
Just wondering if there was a reason this is still pinned to < 2.6-dev, while doctrine/orm is < 2.7-dev? A few of my apps use the zf2 module, the rest bring in the orm directly, and I noticed the proxies being generated differently for each. So I pinned my common version to 2.5.\* for now.

**Comment by Ocramius** [comment]
No real reason, can be bumped to `~2.4` IMO /cc @gianarb

**Comment by gianarb** [comment]
Thanks! I work about it!

**Comment by TomHAnderson** [comment]
This module willl be bumped to 2.8.1 along with the latest in other doctrine libraries
