### ISSUE TITLE
Zend Developer Toolbar integration redesign

### ISSUE THREAD

**Issue by sebfek** [doctrine/DoctrineModule#550]
I think the zend dev. toolbar integration need a redesign. I must say honestly I never read the query until now only the query counter/time, because it's really diffficult to read the queries itself (tons of generated fields). I mostly just interested in which query method is called like UserRepository::find(4) or whatever. I don't know if this is possible to find out in the hooks anyway but I think a lot of users find it better this way. When this is not possible then some sql highlighting and expandable areas make the toolbar lot better.

**Comment by TomHAnderson** [comment]
Please submit a PR for your idea if you're still interested.
