### ISSUE TITLE
Hydration of relations with underscore (snake case) names

### ISSUE THREAD

**Issue by floriandammeyer** [doctrine/DoctrineModule#554]
One of my entities has a one-to-many association called 'rented_items' with its corresponding setters and getters.

```
/**
 * @ORM\Entity
 */
class Rental
{
    // ...
    /**
     * @ORM\OneToMany(targetEntity="RentedItem", mappedBy="rental")
     * @var ArrayCollection $rented_items
     */
    protected $rented_items;
    // ...
    public function removeRentedItems($rented_items)
    {
        // ...
    }
    public function addRentedItems($rented_items)
    {
        // ...
    }
}
```

Unfortunately, the pull request https://github.com/doctrine/DoctrineModule/pull/539 seems not to have solved the issue with snake_case fields for associations. Doctrine (running DoctrineModule 1.0.0) throws the following error at me:

> LogicException
> 
> File:
> 
> ```
> /vagrant/app/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/Strategy/AllowRemoveByValue.php:51
> ```
> 
> Message:
> 
> ```
> AllowRemove strategy for DoctrineModule hydrator requires both addRented_items and removeRented_items to be defined in Entity\Rental
>                      entity domain code, but one or both seem to be missing
> ```

**Comment by TomHAnderson** [comment]
It is obvious to me you have misnamed your getter and setter. 

Given a (very) old style property name containing an underscore, in this case `$rented_items` the getter, if you are using canonical naming and which Doctrine expects of your code, is `getRented_Items` (reminder PHP functions are case insensitive so `getrented_items` is valid too).  So the problem does not lie with Doctrine.  Your use of canonical naming needs to be addressed.

**Comment by floriandammeyer** [comment]
@TomHAnderson 
I don't think that I have 'obviously' misnamed my getter and setter. The consensus on the internet seems to be that snake_case is converted to camelCase/PascalCase by omitting the underscores and capitalizing the first letter of each word that was initially separated by the underscores, i. e. compare with https://en.wikipedia.org/wiki/PascalCase or this JavaScript library https://github.com/blakeembrey/snake-case. 

Therefore rented_items becomes rentedItems or RentedItems, not Rented_items. Doctrine's conversion of naming styles is too simple here, because it merely capitalizes the first letter and ignores everything else, which does not follow the widely accepted way of converting snake_case to PascalCase.
