### ISSUE TITLE
Issues running tests with this module

### ISSUE THREAD

**Issue by danbroooks** [doctrine/DoctrineModule#555]
Is there any guidance with regards running integration tests with this module? I'm trying to create some tests for factory classes that are a part of my project, however nearly all of these classes eventually boil down to instantiating a repository.

I have got my project set up to successfully run a suite of tests when it is pointing at a database, but when the code goes off to CI it tries to run without the database configuration (db config not stored as part of project repository), and therefore fails when trying to create the entity manager (An abstract factory could not create an instance of doctrine.entitymanager.ormdefault). I've looked and there doesn't seem to be any kind of 'stub' EntityManager I could use (looked at swapping out the driverClass). FYI these tests don't actually hit the database, but requires does this module to run.

Is a potential solution to create my own stub driver?

**Comment by TomHAnderson** [comment]
Create a sqlite database in memory and run your migrations against it as part of your tests.
