### ISSUE TITLE
Proxies not compatible with Parent

### ISSUE THREAD

**Issue by Michal-sk** [doctrine/DoctrineModule#566]
Is it a known issue that Proxies are not compatible with Parents when using return types in PHP70? The proxies don't inherrit the return types from the Parents and are therefore not compatible, which returns a fatal error.

**Comment by Ocramius** [comment]
This has been fixed in https://github.com/doctrine/common/issues/606 last year, see https://github.com/doctrine/common/pull/376

**Comment by Michal-sk** [comment]
When would you expect 2.6 to come out?

**Comment by Ocramius** [comment]
@Michal-sk 2.6 was already released.

**Comment by Michal-sk** [comment]
but it does not seem to be tagged, therefore i can not use the version in composer when minimum stability is stable.

**Comment by Ocramius** [comment]
@Michal-sk [`2.6.1`](https://github.com/doctrine/common/releases/tag/v2.6.1) was released in December 2015

**Comment by Michal-sk** [comment]
Problem 1
    - The requested package doctrine/orm ^2.6 is satisfiable by doctrine/orm[2.6.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by Ocramius** [comment]
What you want is `doctrine/common:^2.6.1`. Doctrine ORM does not need to be upgraded to make return type declarations work.

**Comment by Michal-sk** [comment]
Ok, thanks
