### ISSUE TITLE
Recursive references

### ISSUE THREAD

**Issue by JCSama** [doctrine/DoctrineModule#583]
I've tried DoctrineObject::hydrateByReference() with the following example : 
-- Category (with data)
---|--- ID (not empty)
---|--- Name (not empty)
---|--- Products (collection of Product)
-------|--- ID (not empty)
-------|--- Name (not empty)
-------|--- Category (not empty)
-----------|--- ID (not empty)
-----------|--- **Name (EMPTY) this will overwrite the original name**  and that's the problem, I don't 

want that to happen.

To solve this I just added a few lines : 
```
...
        if (is_object($tryObject)) {
            $object = $tryObject;
        }
        // Here
        $objectHash = spl_object_hash($object);

        if (isset($this->visitedObjects[$objectHash])) {
            return $this->visitedObjects[$objectHash];
        } else {
            $this->visitedObjects[$objectHash] = $object;
        }

        foreach ($data as $field => $value) {
...
```

**Comment by TomHAnderson** [comment]
Hi @JCSama ,

In order to contribute patches or fixes please create a Pull Request and include a unit test to validate the change.
