### ISSUE TITLE
Interface caching

### ISSUE THREAD

**Issue by guru888** [doctrine/DoctrineModule#584]
Hi, I want to speed up my application. So I have installed APC with doctrine2 - ZF2. Caching is working fine. Proxies are generated for all the entities.  But I have one interface under entities, the proxy for this interface is not created. So it is throwing a mapping error. Any idea how to resolve this issue.

**Comment by TomHAnderson** [comment]
Does this belong in DoctrineModule or DoctrineORMModule?

Please narrow down the problem for any assistance.

**Comment by guru888** [comment]
DoctrineORMModule
