### ISSUE TITLE
hydrator.md documentation not ZF3 compatible?

### ISSUE THREAD

**Issue by bartoszzajac** [doctrine/DoctrineModule#586]
I'm trying to build form using Zend Framework 3 like it is explained in [hydrator.md](https://github.com/doctrine/DoctrineModule/blob/master/docs/hydrator.md#a-complete-example-using-zendform). When I'm trying add `fieldset` (like [BrandFieldset in ProductFieldset in docs](https://docs.zendframework.com/zend-form/collections/)) I'm getting blank page.
I was able to dive into with debugger and code crashes in `InvocableFactory.php` from zend-servicemanager. It tries to instantiate `Application/Form/MyFieldset` which has constructor with parameters (`ObjectManager $objectManager`) which are not allowed.
I suppose that this is not incompatibility with ZF3 but inaccurate documentation.

**Comment by TomHAnderson** [comment]
The zendframework/zend-hydrator did cause several changes.  If you can add your documentation to the hydrator.md file as you work though it that would be appreciated.

**Comment by bartoszzajac** [comment]
@TomHAnderson I'm affraid this will be long road for me. But I'm trying.

**Comment by TomHAnderson** [comment]
@bartoszzajac Should I close this issue?

**Comment by bartoszzajac** [comment]
I think so, but I didn't update anything. I resolve my problems but I do not feel strong to write documentation.
