### ISSUE TITLE
Memory leak in v1.2.0

### ISSUE THREAD

**Issue by jstewmc** [doctrine/DoctrineModule#587]
Er, I've been wrong before, but I think I found a memory leak in Doctrine Module 1.2.0:

```php
<?php

require_once realpath(__DIR__ . '/vendor/autoload.php');

use Zend\Mvc\Application;

$config = [
    'modules' => [
        'Zend\\Router', 
        'DoctrineModule'
    ], 
    'module_listener_options' => []
];

echo "Baseline: " . round(memory_get_usage() / 1000000, 2) . " MB\n";

for ($i = 0; $i < 10; ++$i) {
    $a = Application::init($config);
    unset($a);
    gc_collect_cycles();
    echo "After $i: " . round(memory_get_usage() / 1000000, 2) . " MB\n";
}
```
The example above will produce the following output:
```
Baseline: 0.53 MB
After 0: 1.51 MB
After 1: 1.64 MB
After 2: 1.76 MB
After 3: 1.89 MB
After 4: 2.01 MB
After 5: 2.14 MB
After 6: 2.26 MB
After 7: 2.39 MB
After 8: 2.52 MB
After 9: 2.65 MB
```
If you comment out the DoctrineModule module, the example above will produce the following output:
```
Baseline: 0.53 MB
After 0: 1.38 MB
After 1: 1.38 MB
After 2: 1.38 MB
After 3: 1.38 MB
After 4: 1.38 MB
After 5: 1.38 MB
After 6: 1.39 MB
After 7: 1.39 MB
After 8: 1.39 MB
After 9: 1.39 MB
```
We're using Codeception functional tests for our application, and each test gets a new `Application` instance. With lots of entities and after more than 1,200 tests, our staging server is running out of memory.

Has anyone seen (or solved) this issue before? Any help would be appreciated!

By the way, Doctrine is a fantastic library, and I certainly don't mean to find fault. It does all kinds of awesome stuff, and I know it's a huge amount of (mostly unpaid) work to maintain it. Thank you to the community and contributors for all your hard work!

**Comment by Ocramius** [comment]
Heya,

Is this on PHP 5 or PHP 7?

**Comment by jstewmc** [comment]
@Ocramius, 

Oh, ha. Sorry. It's PHP 7.0. 

Here's the full stack if it'll help:

- CentOS Linux release 7.3.1611 (Core)
- nginx/1.11.6
- PHP 7.0.13 (cli) (built: Nov 10 2016 22:33:41) ( NTS )
  - Zend Engine v3.0.0
  - Zend OPcache v7.0.13
- zendframework/zendframework 3.0.0
- doctrine/doctrine-module 1.2.0

Thank you for the quick response.

**Comment by Ocramius** [comment]
There is one unavoidable leak, which needs fixing in doctrine/annotations by removing the need to register a loader manually (see https://github.com/doctrine/DoctrineModule/blob/184ea28eae94baad8825a515de9866458de0c622/src/DoctrineModule/Module.php#L54-L58)

The other one I can think of is here: https://github.com/doctrine/DoctrineModule/blob/184ea28eae94baad8825a515de9866458de0c622/src/DoctrineModule/Module.php#L66

Can you try running a `gc_collect_cycles()` in-between instantiations, and check memory usage then?

A test script that we can use would also be cool, and should be relatively trivial to add...

**Comment by jstewmc** [comment]
Hmm, it looks like it's the second possibility.

I instantiated a new service manager on [line 66 in DoctrineModule/Module.php](https://github.com/doctrine/DoctrineModule/blob/184ea28eae94baad8825a515de9866458de0c622/src/DoctrineModule/Module.php#L66), instead of using the Application's service manager:

```php
/**
 * {@inheritDoc}
 */
public function onBootstrap(EventInterface $event)
{
    // $this->serviceManager = $event->getTarget()->getServiceManager();
    $this->serviceManager = new \Zend\ServiceManager\ServiceManager();
}
```
When I ran the script from my previous comment, it produced the following output:
```
Baseline: 0.53 MB
After 0: 1.39 MB
After 1: 1.39 MB
After 2: 1.39 MB
After 3: 1.39 MB
After 4: 1.39 MB
After 5: 1.39 MB
After 6: 1.39 MB
After 7: 1.4 MB
After 8: 1.4 MB
After 9: 1.4 MB
```
The script I'm using (and pasted above) is calling `unset()` and `gc_collect_cycles()` between each `Application` instantiation. So, if it can, PHP should be releasing the application instance from memory. It can't. So, there must be some of circular reference.  

To be fair, I don't think this is just a DoctrineModule issue. Wouldn't this be across the entire Zend Framework? Wouldn't _any_ object which stores a reference to the service manager that is then available through the service manager create a circular reference? 

In our case:

1. the _doctrine module_ keeps a reference to the application's _service manager_;
2. the _module manager_ keeps a reference to the _doctrine module_;
3. the _service manager_ keeps a reference to Zend's _module manager_;

Even when the _application_ instance drops out-of-scope:

1. The _application_ can't be destructed, because the _service manager_ can't be destructed. 
2. The _service manager_ can't be destructed, because the _module manager_ can't be destructed. 
3. The _module manager_ can't be destructed, because the _doctrine module_ can't be destructed. 
4. The doctrine module can't be destructed, because it contains a reference to the _service manager_. 

It's circular. 

It seems like this issue would affect any object in the service manager that stores the service manager as a property, either directly or indirectly. 

What do you think?

**Comment by jstewmc** [comment]
I'm going to go ahead and close this issue. 

It's not DoctrineModule-specific. _Any_ object referenced in the service manager with a reference back to the service manager will create a memory leak. DoctrineModule just happened to be the first module I added in my tests. 

## Our solution
In case someone stumbles upon this thread later, we solved the issue by using Codeception's [Robo task runner](http://codeception.com/docs/12-ParallelExecution) to run groups of ~100 tests one-after-another (we couldn't get parallel tests to work because of database deadlocks). The groups of tests run in separate PHP processes, and PHP reclaims the leaked memory after each group on process shutdown. Using these groups, we reduced test time for 1,200 functional tests from 80 minutes to 20 minutes. 

## The solution
In the grand scheme of things, here's a possible solution for this issue;

1. Create a new interface, 'Destructable', for any service in the service manager that, in turn, references the service manager. It would require a public `destruct()` method (note, not the magic one). Of course, it would be up to the component author to implement the `destruct()` method's details.
2. Add a `destruct()` method to the `ServiceManager`. When called, the service manager would loop through all of its instantiated services, check for those that implement the `Destructable` interface, and call the `destruct()` method of the ones that did. 
3. Add a `destruct()` method to the `Application`. When called, it would call the service manager's `destruct()`. 

Obviously, if I'm the only person with this problem, the cost/benefit of this huge change just doesn't make sense. But, if it's a wider community issue, I think this is a possible solution. 

Either way, thank you for your help and hard work @Ocramius!

**Comment by Ocramius** [comment]
This does not need fixing, and neither in zf or any lib. Cycle collection
is something done by PHP anyway, and any heavy or long-running task should
do it anyway.

Designing for cycle GC is not possible in userland, unless we want to get
rid of the advantages brought in by a GC'd language: just drop a
`gc_collect_cycles()` hook into your testing framework instead.
