### ISSUE TITLE
 Is it planned to integrate with Zend Expressive?

### ISSUE THREAD

**Issue by drakulitka** [doctrine/DoctrineModule#596]
Hello, great module !!! Do you plan to develop a similar module for Zend Expressive?

**Comment by manuakasam** [comment]
You won't need doctrine-module for this.
Simply run `composer require dasprid/container-interop-doctrine` and you
can access your stuff via `$container->get(EntityManager::class)` (assuming
correct use statement ;) )

**Comment by drakulitka** [comment]
I did not find the implementation of doctrine-migrations in this module!
There are many ways to introduce doctrine
https://xtreamwayz.com/blog/2015-12-12-setup-doctrine-for-zend-expressive

I would like to use all the functionality of this module in Zend Expressive ^ 2.0

**Comment by manuakasam** [comment]
Migrations are also not a default set of doctrineModule ;)

`composer require doctrine/migrations` and then `./vendor/bin
doctrine:migrations`

Also word of advise: don't blindly use libraries. Check what the libraries
are doing! It is fairly simple to use doctrine on it's own without using a
thing like DoctrineModule. DoctrineModule is simply heavily tied into Zend
Framework which is netting you some advantages (like the Form Element).

**Comment by drakulitka** [comment]
Thanks for the advice. I will try to stick to it!

**Comment by twmobius** [comment]
How about Validators/ Hydrators?
