### ISSUE TITLE
Hydrator set empty strings instead on nulls

### ISSUE THREAD

**Issue by matiasiglesias** [doctrine/DoctrineModule#598]
I'm hydrating an entity with an array with values from a form post. 
For example:
`$arr = [id=>1, field1=>''];`
If my entity has a field2 that fields is set to null, but field1 is set to '' (empty string).
Is there any way to force empty string to null values?
Thanks

**Comment by Ocramius** [comment]
This is up to the input filter, not the hydrator. The hydrator will just
take given values and blindly stuff them into an object. Validity is up to
the consumer.

**Comment by matiasiglesias** [comment]
If doctrine notatiion sets default to null I think empty strings would be saved as null, but Im gonna resolve it via Filter as you said. Thanks
