### ISSUE TITLE
Hydrate simple select field instead of ObjectSelect + Typeahead

### ISSUE THREAD

**Issue by koseduhemak** [doctrine/DoctrineModule#600]
Hello,

i am trying to hydrate a select field. The reason I cannot use ObjectSelect is, that there are too many values the user can choose from (browser gets stuck). Therefore I implemented a "typeahead" functionality on a select field to retrieve data while the user is typing... A user can now click on results to his query and one or more selected values getting set.

![bildschirmfoto 2017-06-30 um 18 28 35](https://user-images.githubusercontent.com/12804757/27744983-ff02eaec-5dc1-11e7-887c-0dc1a0b3cbae.png)

Code in Entity:
`/**
     * @var Collection
     * @ORM\ManyToMany(targetEntity="Search\Entity\Artist")
     */
    protected $randomArtists;`

Then he tries to send the form and Doctrine's hydration strategy fails: 
Warning: array_udiff(): Argument #2 is not an array in ...../vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/Strategy/AllowRemoveByValue.php on line 68

I debugged that line already and it seems, that second argument "$collection" is null instead of array.
Is this intended behavior or a bug?
Is there any way to hydrate an plain select field? I also wrote a custom validator which looks up in the specific table, if the provided values are existing - so no security risks here.

Do I have to code a custom form field which behaves like ObjectSelect, but can cope with this sort of lazy loading?

Sincerly koseduhemak

**Comment by TomHAnderson** [comment]
ObjectSelect is not intended to be paginated so to solve your problem by pagination you'll need another solution, like your custom for field.
