### ISSUE TITLE
Don't display progress output in migration commands

### ISSUE THREAD

**Issue by bupy7** [doctrine/DoctrineModule#603]
After done `migrations:migrate` command nothing display progress output im my console like as doc (http://docs.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/managing_migrations.html):

```
$ ./doctrine migrations:migrate
Are you sure you wish to continue?
y
Migrating up to 20100416130452 from 0

  >> migrating 20100416130452

     -> CREATE TABLE users (username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL) ENGINE = InnoDB

  >> migrated
```

My output:

```
$ php bin/console migrations:migrate
Loading configuration from the integration code of your framework (setter).
                                                                    
                    Doctrine Database Migrations                    
                                                                    
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
```

Is it normal?

Packages:

doctrine/doctrine-module: 1.2.0
doctrine/doctrine-orm-module: 1.1.3
doctrine/migrations: master
symfony/console: 3.3.6

**Comment by Ocramius** [comment]
What's the exit code? Run it with `-vvv`, check if any code calls an explicit `exit()` or `die()` somewhere

**Comment by bupy7** [comment]
@Ocramius Migrations all works. Just no output. If have errors `-vvv` is working.

**Comment by Ocramius** [comment]
Something causing output buffering? What happens if you echo in the body of a migration?

**Comment by bupy7** [comment]
@Ocramius No output.

**Comment by bupy7** [comment]
> Something causing output buffering? 

No. Other commands like 'orm:info' is working perfect:

```
$ php bin/console orm:info
Found 4 mapped entities:
[OK]   User\Entity\User
[OK]   User\Entity\Telegram
[OK]   Geo\Entity\City
[OK]   Party\Entity\Party
```

**Comment by Ocramius** [comment]
@bupy7 try an `ob_flush()` right after producing the output

**Comment by Ocramius** [comment]
@bupy7 try an `ob_flush()` right after producing the output

**Comment by bupy7** [comment]
@Ocramius No any output. No any errors.

**Comment by Ocramius** [comment]
@bupy7 can you try using `error_log()` and printing something to STDERR?

**Comment by bupy7** [comment]
@Ocramius It's working.

**Comment by Ocramius** [comment]
Right, so something is doing aggressive output buffering. Unsure where to look exactly, but creating an xdebug profile would help a lot in figuring out which parts of your code may be calling any `ob_*` functions

**Comment by bupy7** [comment]
@Ocramius Why only doctrine migrations commands have it the problem?

**Comment by Ocramius** [comment]
@bupy7 don't know without debugging it myself - you need to figure it out on your own first

**Comment by bupy7** [comment]
@Ocramius [zf-app-blank](https://github.com/bupy7/zf-app-blank) have the same problem.

**Comment by bupy7** [comment]
@Ocramius Closure message function for some reason is `null` in `Doctrine\DBAL\Migrations\OutputWriter`. I made that:

```php
public function __construct(\Closure $closure = null)
    {
        if ($closure === null) {
            $closure = function($message) {echo $message;};
        }
        $this->closure = $closure;
    }
```

And output:

```
$ php bin/console migrations:migrate
Loading configuration from the integration code of your framework (setter).
                                                                    
                    Doctrine Database Migrations                    
                                                                    

WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
Migrating <info>up</info> to <comment>20170816064411</comment> from <comment>0</comment>
  <info>++</info> migrating <comment>20170816064411</comment>
This is message UP!<error>Migration 20170816064411 was executed but did not result in any SQL statements.</error>
  <info>++</info> migrated (0.18s)
  <comment>------------------------</comment>
  <info>++</info> finished in 0.18s  <info>++</info> 1 migrations executed  <info>++</info> 0 sql queries
```

**Comment by bupy7** [comment]
@Ocramius On line 48 in `DoctrineOrmModule\Service\MigrationsConfigurationactory::_invoke()` configuration got `NULL` value for `OutputWriter`. After in all calls `Doctrine\DBAL\Migrations\Tools\Console\Command::getMigrationConfiguration()`had a singleton of `Doctrine\DBAL\Migrations\Configuration`. Message in console `Loading configuration from the integration code of your framework (setter).` confirms this.

**Comment by bupy7** [comment]
Resolve: Replace line 48 in `DoctrineORMModule\Service\MigrationsCOnfigurationFactory` to:

```php
$output = new \Symfony\Component\Console\Output\ConsoleOutput();
$writer  = new \Doctrine\DBAL\Migrations\OutputWriter(function ($message) use ($output) {
    return $output->writeln($message);
});
$configuration    = new Configuration($connection, $writer);
```

**Comment by TomHAnderson** [comment]
It looks like you're ready to create a PR @bupy7 ?

**Comment by bupy7** [comment]
@TomHAnderson Yes, I do.

**Comment by TomHAnderson** [comment]
Fixed with https://github.com/doctrine/DoctrineORMModule/pull/528
