### ISSUE TITLE
There are no commands defined in the "orm:schema-tool" namespace.

### ISSUE THREAD

**Issue by theoaks** [doctrine/DoctrineModule#618]
I get this error when I try to run the command

`doctrine orm:schema-tool:create`

There are no commands defined in the "orm:schema-tool" namespace.

What am I doing wrong?

**Comment by theoaks** [comment]
Just realized this is not the right place to post it... I will raise it under the mail doctrine project

**Comment by Ocramius** [comment]
You also need DoctrineOrmModule

**Comment by theoaks** [comment]
Thanks

**Comment by theoaks** [comment]
Do you mean doctrine/doctrine-orm-module.

I have tried to install that, but it failed.

Here's the dump from cli

`Problem 1
    - doctrine/doctrine-orm-module 1.1.0 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0].
    - doctrine/doctrine-orm-module 1.1.1 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0].
    - doctrine/doctrine-orm-module 1.1.2 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0].
    - doctrine/doctrine-orm-module 1.1.3 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0].
    - doctrine/doctrine-orm-module 1.1.4 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0].
    - doctrine/doctrine-orm-module 1.1.5 requires doctrine/doctrine-module ^1.2 -> satisfiable by doctrine/doctrine-module[1.2.0].
    - Conclusion: don't install doctrine/doctrine-module 1.2.0
    - Installation request for doctrine/doctrine-orm-module ^1.1 -> satisfiable by doctrine/doctrine-orm-module[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5].`

Is there a flag I need to turn on to enable the module?

Here's my cli-config.php code

`require "vendor/autoload.php";

use Doctrine\ORM\Tools\Console\ConsoleRunner;

$entityManager = \Oaks\Core\DatabaseHelper::getEntityManager();

$platform = $entityManager->getConnection()->getDatabasePlatform();
$platform->registerDoctrineTypeMapping( 'enum', 'string' );

return ConsoleRunner::createHelperSet( $entityManager );`

I'm not using ZendFramework

**Comment by TomHAnderson** [comment]
This is a Zend Framework module.  You'll have to manually configure your object manager and command line tool.
