### ISSUE TITLE
suppressing output

### ISSUE THREAD

**Issue by basz** [doctrine/DoctrineModule#619]
I'm trying to silence the migrations:migrate command completely...

However even overriding the ConsoleRunner with my own application setup and passing a NullInput to its run method and adding the --quiet options will still generate a lot of noise.

capturing with ob_start does not work either.

why? I'm trying to write a phpunit test that clears all tables and reruns migrations between tests and would like to suppress output in the tests.

**Comment by TomHAnderson** [comment]
Migrations are handled by doctrine/doctrine-orm-module.  

But to answer your question here, what works for me with fixtures and schema is to write it in to the Bootstrap.  The code to handle it is at `migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php`

Write your own migration handing and you can remove all the output.

**Comment by TomHAnderson** [comment]
So I remembered how I did this.  Use the binary .phar and you can control the output.

Tom

**Comment by basz** [comment]
Turns out it isn't hard to do without the MigrationCommand;

```
$readModelConnection = self::getContainer()->get('doctrine.connection.default');
if (! self::$migrationsSql) {
    self::$migrationsSql = "SET FOREIGN_KEY_CHECKS = 0;\n";
    foreach ($readModelConnection->query('SHOW TABLES')->fetchAll(\PDO::FETCH_COLUMN) as $tableName) {
        self::$migrationsSql .= sprintf("DROP TABLE %s;\n", $tableName);
    }
    self::$migrationsSql .= "SET FOREIGN_KEY_CHECKS = 1;\n";
    $readModelConnection->prepare(self::$migrationsSql)->execute();
    $configuration = new Configuration($readModelConnection);
    $configuration->setMigrationsNamespace('HF\Api\Migrations');
    $configuration->setMigrationsDirectory('migrations');
    $migration = new Migration($configuration);
    $migrationsSql = '';
    foreach ($migration->getSql() as $version => $sqlSet) {
        foreach ($sqlSet as $sql) {
            $migrationsSql .= sprintf("%s;\n", $sql);
        }
    }
    $readModelConnection->prepare($migrationsSql)->execute();
    self::$migrationsSql .= $migrationsSql;
} else {
    $readModelConnection->prepare(self::$migrationsSql)->execute();
}
```
The beef being of course;
```
$configuration = new Configuration($readModelConnection);
$configuration->setMigrationsNamespace('HF\Api\Migrations');
$configuration->setMigrationsDirectory('migrations');
$migration = new Migration($configuration);
foreach ($migration->getSql() as $version => $sqlSet) {
  foreach ($sqlSet as $sql) {
```

**Comment by TomHAnderson** [comment]
You can also use the migrations.phar and run the migrations from the command line, but I like your coding way of doing it better.
