### ISSUE TITLE
What is the purpose of pre-releases?

### ISSUE THREAD

**Issue by Slamdunk** [doctrine/DoctrineModule#621]
Hi, it's 1 year and a half that version 2 is out, but as a pre-release, and I would like a lot to have it in my codebase, but since both the main modules `DoctrineORMModule` and `DoctrineMongoODMModule` both require 1.2, how could we precisely test those pre-releases?

**Comment by TomHAnderson** [comment]
That's a great point for a pre-release.  We'll need to stage a release for DoctrineORMModule to use 2.0 series first and release them together.  We'll need to get the MongoODM team on board too.

**Comment by thomasvargiu** [comment]
Please don't use pre-release, is not supported by packagist/composer and it's not [semver](https://semver.org/) compatible I guess.
Should be better to use `-alpha`, `-beta`, `-RC` tags?

**Comment by TomHAnderson** [comment]
Thanks for the advice.  There are two issues I want to see fixed and the next release will not be a pre-release.
