### ISSUE TITLE
Use Inflector::classify() instead of ucfirst() in AllowRemoveByValue

### ISSUE THREAD

**Issue by ariddlestone** [doctrine/DoctrineModule#623]
I'm aware naming issues keep coming up, but I just hit one I haven't yet seen mentioned...

Currently DoctrineModule\Stdlib\Hydrator\DoctrineObject uses Doctrine\Common\Util\Inflector::classify() to identify the getter and setter methods for fields, while DoctrineModule\Stdlib\Hydrator\Strategy\AllowRemoveByValue uses ucfirst() to identify the adder and remover methods for associations.

This leads to some inconsistency in how we name our methods. For example, a field foo_bar would need methods getFooBar() and setFooBar(), while a one-to-many association foo_bars would need addFoo_bars() and removeFoo_bars().

Shouldn't both use Inflector::classify() to keep consistency (and readability) in class method names? This would lead to the much more pleasing addFooBars() and removeFooBars().

I realise that changing naming conventions could be problematic - I guess a temporary solution would be to extend the strategies myself, override the methods to use the naming conventions above, and add those strategies to the hydrator. This would be easier if there was a separate method to get the adder and remover method names (so I didn't have to override the whole method).

Ideas?

**Comment by TomHAnderson** [comment]
This library is at pre-release 2.0.1 and this move forward for a version 2 of this library is the perfect time to correct the issue you've brought up.  

I think you're right they should use the inflector.  Are you keen to send in a PR?

**Comment by ariddlestone** [comment]
Thanks, I'll give it a shot (not done PRs before, but we'll see how it goes).

**Comment by TomHAnderson** [comment]
Fixed with 2.1.0
