### ISSUE TITLE
orm:ensure-production-settings should complain about all issues at once

### ISSUE THREAD

**Issue by bitwombat** [doctrine/DoctrineModule#637]
Minor issue.

I noticed that when I run:

    doctrine-module orm:ensure-production-settings

It complains:

    [ERROR] Query Cache uses a non-persistent cache driver

And when I fix that, it complains:

    [ERROR] Metadata Cache uses a non-persistent cache driver

When I fix all caches, it then says:

    [ERROR] Proxy Classes are always regenerating.

It would be helpful if it would tell me all of the complaints at once (warnings instead of errors?)

**Comment by driehle** [comment]
Actually, this issues is again not in the right place :-(

`DoctrineModule` only enables the commands offered by doctrine/orm. The command itself is defined here: https://github.com/doctrine/orm/blob/2.10.x/lib/Doctrine/ORM/Tools/Console/Command/EnsureProductionSettingsCommand.php.

And here is the actual implementation of the checks in `Doctrine\ORM\Configuration`: https://github.com/doctrine/orm/blob/416aa1d2d71c8d1796781c3f57b17ba26debde26/lib/Doctrine/ORM/Configuration.php#L519.
