### ISSUE TITLE
Case Sensitivity of 'config'

### ISSUE THREAD

**Issue by kevin2244** [doctrine/DoctrineModule#645]
Hello.

When trying to run this CLI tool:
```
$ vendor/bin/doctrine orm:schema-tool:create
```
I received the following fatal error:
```
ServiceNotFoundException: Unable to resolve service "Config" to a factory...
...ServiceManager.php on line 687
```

The Doctrine Module for Zend Framework has the line:
```
$config      = $serviceLocator->get('Config');
```
in the Doctrine Module file: 
**AbstractDoctrineServiceFactory.php**

Yet the container, as shipped by my recent Zend Expressive 3 install, sets up the config like this:
```
$dependencies['services']['config'] = $config;
```

I know that some changes were made regarding case-sensitivity in v3 of zend-servicemanager, 
however doctrine-module supports it according to its composer.json.

Changing the above line from AbstractDoctrineServiceFactory.php to use the all lower case 'config' stopped the exception and fatal error. 

Not sure if I did something wrong but the problem is repeatable.

**Comment by TomHAnderson** [comment]
I'm comfortable making this change to lowercase `config`.  Would you like to submit a PR?
