### ISSUE TITLE
DoctrineObject::handleTypeConversions receives `$typeOfField` as null for references

### ISSUE THREAD

**Issue by boesing** [doctrine/DoctrineModule#669]
Hey guys, the method `DoctrineObject::handleTypeConversions` receives a `null` value for a reference type. As per phpdoc, the `$typeOfField` value must contain a string value.

In [DoctrineObject::hydrateValue](https://github.com/doctrine/DoctrineModule/blob/2.1.10/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php#L279) it is being passed as `null` after receiving the type value from the metadata object.
However, the `Metadata` object states to return always a string value (non-nullable) but actually, it returns null for references.
`ClassMetadata` is implemented by `\Doctrine\ORM\Mapping\ClassMetadataInfo` which returns `null` in case it cannot find an appropriate type for a field. Therefore, it changes the typehint to return `string or null`.

Just wanted to mention this as I am running into problems because I call `Type::hasType` with that `null` value on `doctrine/dbal` v2.10 which provides that new strictly typed `TypeRegistry` which does not accept `null` anymore.

Probably I have to point this to `doctrine/dbal` or we're fixing this in `doctrine/orm` by not returning `null` anymore? This seems to be a nasty issue and I dont really know how to fix that. :-/

**Comment by TomHAnderson** [comment]
Hydrators have been moved to https://github.com/doctrrine/doctrine-laminas-hydrator

**Comment by boesing** [comment]
> https://github.com/doctrrine/doctrine-laminas-hydrator

Fixed: https://github.com/doctrine/doctrine-laminas-hydrator
