### ISSUE TITLE
Transition to Laminas

### ISSUE THREAD

**Issue by marc-jangvs** [doctrine/DoctrineModule#670]
Now Zend made it's transition to Laminas the package need to be updated to point to the correct new packages.

**Comment by TomHAnderson** [comment]
I think you're jumping the gun.  Laminas is in a transition period and we can start soon.

I'm the Zend guy at Doctrine which I think will translate to the Laminas guy now.  I would love your help here when it's time if you can spare some effort.

**Comment by Slamdunk** [comment]
A green-build PR is already available: https://github.com/doctrine/DoctrineModule/pull/671

**Comment by dennybrandes** [comment]
Does someone know, when this will be release?

**Comment by TomHAnderson** [comment]
Released v3.0

**Comment by dennybrandes** [comment]
So nice :-)

**Comment by dennybrandes** [comment]
Thanks!
