### ISSUE TITLE
Doctrine-module cli not working in Laminas Mezzio

### ISSUE THREAD

**Issue by pmarko** [doctrine/DoctrineModule#698]
Is there a plan to implement CLI tools for Mezzio or I'm just overlooking something ? By the quick look in to the code I can still see CLI using Laminas MVC.

**Comment by TomHAnderson** [comment]
This is what you want:  https://github.com/Roave/psr-container-doctrine

The Laminas Doctrine modules are for Laminas and not Mezzio.

**Comment by pmarko** [comment]
Thank you Tom for pointing me the right direction.

Anyway, if someone wants to use doctrine-module CLI with Mezzio this is how I achieved it.

In the "project/config" create the directory let's say "doctrine-cli" and in that directory create the file "config.global.php" with following content. This will return merged config from Mezzio ConfigAggregator.

```
<?php
return require __DIR__ . '/../config.php';
```

In the "project/config" create the file "application.config.php" with 

```
<?php

return [
    'modules' => [
        'Laminas\Router',
        'DoctrineModule',
        'DoctrineORMModule',
    ],
    'module_listener_options' => [
        'config_glob_paths' => [
            realpath(__DIR__) . '/doctrine-cli/{{,*.}global,{,*.}local}.php',
        ],
    ],
];
```

This will setup ModuleLoader with the config from doctrine-cli directory. 

Everything now works as should. 

Do not forget install LaminasMvc if not installed yet.
