### ISSUE TITLE
latest release pulls doctrine/orm 2.8.x-dev instead of stable 2.7.3

### ISSUE THREAD

**Issue by JohanMouritsen** [doctrine/DoctrineModule#704]
i am not sure why it happens but when i use specifically:
"doctrine/doctrine-module": "^4.0.3",
it decides to install doctrine/orm 2.8.x-dev

while if i use:
"doctrine/doctrine-module": "4.0.2",
 it installs doctrine/orm 2.7.3

here is my full list of requires in composer json:
"require": {
        "php": "^7.3.1",
        "laminas/laminas-component-installer": "^2.2.0",
        "laminas/laminas-mvc": "^3.1.1",
        "laminas/laminas-mvc-form": "^1.0",
        "laminas/laminas-form": "^2.15.0",
        "laminas/laminas-json": "^3.1.2",
        "laminas/laminas-log": "^2.12.0",
        "laminas/laminas-cache": "^2.9.0",
        "laminas/laminas-mvc-console": "^1.2.0",
        "laminas/laminas-mvc-i18n": "^1.1.1",
        "laminas/laminas-mvc-plugins": "^1.0.1",
        "laminas/laminas-session": "^2.9.3",
        "laminas/laminas-servicemanager-di": "^1.2.1",
        "laminas/laminas-config-aggregator": "1.3.0",
        "laminas/laminas-math": "3.2.0",
        "symfony/validator": "4.0.4",
        "doctrine/doctrine-orm-module": "^3.0.5",
        "doctrine/doctrine-module": "^4.0.3",
        "doctrine/migrations": "^2.2.1",
        "oxfordrisk/entities": "v1.1.28",
        "oxfordrisk/git-hooks": "v1.0.1",
        "oxfordrisk/core": "v1.1.2",
        "zircote/swagger-php": "3.0.4",
        "guzzlehttp/guzzle": "6.3.0",
        "nesbot/carbon": "^2.37.0",
        "beberlei/DoctrineExtensions": "^1.1",
        "mandrill/mandrill": "^1.0",
        "ocramius/proxy-manager": "2.1.0",
        "mongodb/mongodb": "1.4.2",
        "stomp-php/stomp-php": "^4.5",
        "servo/fluidxml": "^1.21"
    },
"require-dev": {
        "laminas/laminas-developer-tools": "^1.1.0",
        "friendsofphp/php-cs-fixer": "^2.14",
        "symfony/console": "v5.1.3",
        "symfony/process": "5.0.4",
        "myclabs/deep-copy": "^1.9",
        "codeception/codeception": "^4.0",
        "codeception/module-rest": "^1.0",
        "codeception/module-phpbrowser": "^1.0",
        "codeception/module-asserts": "^1.1",
        "codeception/phpunit-wrapper": "^8.1",
        "mockery/mockery": "^1.3"
    }

**Comment by TomHAnderson** [comment]
Check your minimum stability setting in your composer.json file.

**Comment by JohanMouritsen** [comment]
thank you that was the issue i had 
"minimum-stability": "dev",
