### ISSUE TITLE
 seems 4.1 was tagged as 4.0.4

### ISSUE THREAD

**Issue by svycka** [doctrine/DoctrineModule#705]
I still can't install 4.0.4 but not an urgent problem as it should be the same as 4.0.2 and I already have it but in case of bugfix I would like to have an installable version but because you created 4.1 I guess no bugfixes will be backported to 4.0.x anyway

**Comment by TomHAnderson** [comment]
4.0.x and 4.1.x are maintained.

**Comment by svycka** [comment]
@TomHAnderson maintained but can't install 4.0.4 nor 4.0.3

**Comment by kokspflanze** [comment]
i think its the same problem like in https://github.com/doctrine/doctrine-laminas-hydrator/pull/14

we need to change some dependencies
```
        "doctrine/persistence": "^1.3.7 || ^2.0.0",
        "doctrine/inflector": "^1.4.3 || ^2.0.3",
```

Many ppl has that problem, if you compare the downloads of [4.0.2](https://packagist.org/packages/doctrine/doctrine-module/stats#4.0.2) and [4.1.0](https://packagist.org/packages/doctrine/doctrine-module/stats#4.1.0).
Than you see that most ppl still use the 4.0.2 and nobody use 4.1.0.

I think `doctrine/inflector` v2 is only in orm2.8 and that version is not released. [release-list](https://github.com/doctrine/orm/releases)

**Comment by TomHAnderson** [comment]
Correct, @kokspflanze . A PR was submitted for ORM 2.8 which should have been put in cold storage.  But, instead, it was merged.  That's the root cause of the 4.1.0 branch.

4.0.4 should be installable AND the 4.0.x branch will continue to be maintained.

**Comment by TomHAnderson** [comment]
See the release notes for 4.0.4: https://github.com/doctrine/DoctrineModule/releases/tag/4.0.4

**Comment by kokspflanze** [comment]
@TomHAnderson yes i saw that problem.

but still we have https://github.com/doctrine/DoctrineModule/blob/4.0.4/composer.json#L53-L54 in 4.0.4 and same in 4.1.0
The problem i mention is also for [4.0.4](https://packagist.org/packages/doctrine/doctrine-module/stats#4.0.4).

The change of the composer.json should fix that problem.
Or is the support for orm2.7 stopped?

**Comment by svycka** [comment]
@TomHAnderson I guess you did not understand the issue. I am saying that 4.1.0, 4.0.3, and 4.0.4 same version all of those versions tagged the same commit https://github.com/doctrine/DoctrineModule/commit/ade52811bf990cf0f739b5f026cfb09e5ddf9742
![image](https://user-images.githubusercontent.com/1270782/98642374-0db36980-2336-11eb-84a2-0ce434387bea.png)

**Comment by TomHAnderson** [comment]
Got it.  I'll release a 4.0.5 soon

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/DoctrineModule/releases/tag/4.0.5

`composer update` will update to v4.0.5
The release shows out of sort order in the releases because, I think, releases are sorted by their order in the commit tree.

**Comment by TomHAnderson** [comment]
4.0.5 has issues with Composer 2.  Expect a new release to fix that.

**Comment by svycka** [comment]
not tested but I hope you did right :+1:
