### ISSUE TITLE
latest 4.x.y no longer supports doctrine/persistence ^2.0, preventing doctrine/orm ^2.8

### ISSUE THREAD

**Issue by rtek** [doctrine/DoctrineModule#723]
I cannot use `doctrine/orm ^2.8` with the latest releases for 4.x.y due to conflict on `doctrine/persistence`. 

Related: https://github.com/doctrine/DoctrineORMModule/issues/635

Reviewing the tags:

* `4.0.3` added `doctrine/persistence ^2.0` 
* `4.0.5` reverted to `doctrine/persistence ^1.3`
* `4.1.0` added `doctrine/persistence ^2.0` 
* `4.1.1` reverted to `doctrine/persistence ^1.3`

Should `^4.1` and/or `^4.0` be compat with `doctrine/persistence ^2.0`?

**Comment by driehle** [comment]
@rtek The issue with the broken 4.0.3 release is explained here: https://github.com/doctrine/DoctrineModule/releases/tag/4.0.4. Unfortunately, and I think that is the problem, they have not revoked the 4.0.3 release, though they should have.

Now, unfortunately, again an error was made by publishing 4.1.1. That release has been tag from the 4.0.x branch, likely a simple mistake. Please see discussion in https://github.com/doctrine/DoctrineModule/pull/720 and https://github.com/doctrine/DoctrineModule/pull/722#issuecomment-758607492. The 4.1.1 need to be revokes and a 4.1.2 should be released.

**Comment by rtek** [comment]
@driehle perfect - thanks for stringing this together for me since I was getting lost. `doctrine/doctrine-module ^4.1, != 4.1.1` did the trick.

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/DoctrineModule/pull/720

**Comment by TomHAnderson** [comment]
Here is the 4.1.2 release.  I'm working with the Doctrine team to remove the 4.1.1 release.

https://github.com/doctrine/DoctrineModule/releases/tag/4.1.2

**Comment by rtek** [comment]
4.1.2 works.
