### ISSUE TITLE
Cannot migrate to PHP 8 due to laminas-console dependency.

### ISSUE THREAD

**Issue by bfoosness** [doctrine/DoctrineModule#724]
If you want to use the Doctrine CLI tools in Laminas, this library suggests installing https://github.com/laminas/laminas-mvc-console, which depends on https://github.com/laminas/laminas-console. The former supports PHP 8 but the latter does not, and both are now archived and will not receive updates.

Are there plans to migrate this library and DoctrineORMModule to https://github.com/laminas/laminas-cli? I've looked into this a bit already and would be happy to create a PR for further discussion, but I first want to make sure there's not a better approach.

Thank you

**Comment by bfoosness** [comment]
@TomHAnderson, do you have any thoughts on this? Thanks!

**Comment by TomHAnderson** [comment]
You're the first to bring up this issue.  A PR to enable the Symfony Console commands in DoctrineORMModule, for example, would be welcome.  If laminas-cli can enable the Symfony commands then that would be fine.  I don't have anything else to add that the readme here does not already say: https://github.com/laminas/laminas-console

**Comment by bfoosness** [comment]
I believe the issue is due to a combination of factors, which is probably why this hasn't been brought up before. Our codebase also uses Laminas API Tools, which relies on laminas-api-tools/api-tools-content-negotiation.

https://github.com/laminas-api-tools/api-tools-content-negotiation/blob/1.5.x/config/module.config.php#L46 overrides the `Request` factory, and https://github.com/laminas-api-tools/api-tools-content-negotiation/blob/1.5.x/src/Factory/RequestFactory.php#L32 relies on laminas-console to instantiate a console request.

Because DoctrineModule and DoctrineORMModule commands are currently treated as Laminas requests, they are intercepted by the above code, which will generate an error if laminas/laminas-console is not installed because `Laminas\Console\Request` does not exist.

Using laminas-cli would sidestep this issue because command execution isn't routed as a Laminas request. It hands off execution directly to Symfony instead: https://github.com/laminas/laminas-cli/blob/1.2.x/bin/laminas#L53

**Comment by TomHAnderson** [comment]
You've got my go-ahead to convert to `laminas-cli`.  Good luck!

**Comment by driehle** [comment]
From my understanding, there is no need for a migration to `laminas-cli`. The functionality provided currently using `laminas-mvc-console` is fully provided by the `bin/doctrine-module` script as well. Therefore, for a new major release, i.e. 5.0, I think we would safely drop the `laminas-mvc-console` related features and hint users to execute `./vendor/bin/doctrine-module` instead of `php public/index.php` as it was common for `laminas-mvc-console`.

**Comment by bfoosness** [comment]
You're correct. Our issue is really a conflict between this module and the laminas-api-tools' repository mentioned above, and the fix does really belong in their repository. I have an open issue in that repository to try to resolve this. I thought that perhaps supporting laminas-cli in this module would be helpful (and it would sidestep this issue), but that's really unnecessary once the root issue in the other repository is resolved. I will close this issue out. Thanks!
