### ISSUE TITLE
Unit tests should be executed with PHP 8.0

### ISSUE THREAD

**Issue by driehle** [doctrine/DoctrineModule#740]
I think I might have found a suitable approach for getting unit tests running with PHP 8.0. 

I'd like to discuss the changes proposed in https://github.com/doctrine/DoctrineModule/pull/739 with you. First, as discussed on Slack, we are using symbols from laminas-(mvc-)console in `src` without required that package explicitly (it is in `suggest`, though). Therefore, at first, I have identified these placed, added an appropriate check on top of the file and use `trigger_error` to generate a runtime error in case someone tries using that classes without having the suggestion installed.

Next, I have deprecated the related symbols so that we can remove them with the next major version. To allow running the unit tests with PHP 8, I used `--ignore-platform-req=php`. I know that this is not the best choice, but I think we don't really have a chance to do otherwise. Besides laminas-(mvc-)console, there is laminas-cache as well, which still isn't fully PHP8-compatible (at lest withouth manually replacing legacy cache adapters, see docs).

Personally, I think we can go this way. I cannot think of a scenario where this will break someones application. We are continuing to support under PHP 7.3 & 7.4 what we have supported before and we are continuing not to support under PHP 8.0 what we have never supported before. What do you guys think? 

cc @TomHAnderson @greg0ire

**Comment by greg0ire** [comment]
Hi! I think I have found a BC-break, but I'm unsure of its impact. Besides that, the PR looks good.
