### ISSUE TITLE
incompatible with doctrine/orm >= 2.12.0

### ISSUE THREAD

**Issue by BigMichi1** [doctrine/DoctrineModule#774]
today we updated all dependencies to the latest versions by running `composer update` and faced an issue that broke the application.

we could track it down to the `doctrine/orm` dependency that was upgraded from 2.11.2 to 2.12.0.

the issue here is that in https://github.com/doctrine/DoctrineModule/blame/5.1.x/src/Service/DriverFactory.php#L75-L76 the check uses the "old deprecated" classes which are now abstract. for 2.12.0 `AnnotationDriver` should be used from `Doctrine\ORM\Mapping\Driver` instead of `Doctrine\Persistence\Mapping\Driver`.

currently it does not pass the check and goes to the else and tries in our case to create an instance of `Doctrine\Persistence\Mapping\Driver\AnnotationDriver` by passing the path as the first param where an instance of a Reader is expected and later fails with

     Specifying the paths to your entities is required when using Doctrine\ORM\Mapping\Driver\AnnotationDriver to retrieve all class names.

when paths are checked

**Comment by ppaulis** [comment]
I can try to prepare a fix for this. Is it supposed to support both drivers, as long as the deprecated one exists? Or is the new one sufficiant?

**Comment by ppaulis** [comment]
The PR makes it compatible to the new version of the AnnotationDriver, but no longer the old one. If compatibility for both is still needed, just let me know :-)

**Comment by driehle** [comment]
Fixed with release of ORM 2.12.1, added conflict in #778
