### ISSUE TITLE
Missing Versions on Packagist

### ISSUE THREAD

**Issue by FabianKoestring** [doctrine/DoctrineModule#783]
Hey there,

`5.1.1` cant be found on packagist.
https://packagist.org/packages/doctrine/doctrine-orm-module

**Comment by driehle** [comment]
The link you provided is DoctrineORMModule, which has 5.1.0 as the latest version. For DoctrineModule the latest version 5.1.1 is displayed here: https://packagist.org/packages/doctrine/doctrine-module.

**Comment by FabianKoestring** [comment]
Oh man! Iam sry. 😑🤦‍♂️
