### ISSUE TITLE
Release 5.3.0 with PHP 8.2 Support

### ISSUE THREAD

**Issue by rogervila** [doctrine/DoctrineModule#798]
Hello,

The 5.3.x branch includes PHP 8.2 Support, but 5.3.0 has not been yet released. 

Is there any plan to create the release soon? If it needs to be tested I can help with it.

Thank you!

**Comment by driehle** [comment]
Would be glad if you could provide feedback to #796, besides documentation that'd be the last thing I'd like to bring into 5.3.0.

**Comment by rogervila** [comment]
Hi @driehle,

After the discussion on #796, we decided to postpone the PR merge for a future version and release the `5.3.0` version that contains PHP 8.2 Support.

Could you create the release? Let me know if there is something else I can do from my side.

Thank you!

**Comment by rogervila** [comment]
> Hi @driehle,
> 
> After the discussion on #796, we decided to postpone the PR merge for a future version and release the `5.3.0` version that contains PHP 8.2 Support.
> 
> Could you create the release? Let me know if there is something else I can do from my side.
> 
> Thank you!

Hi @Ocramius, could you tag the release if @driehle is not available? 

Thank you!

**Comment by Ocramius** [comment]
No: this is @driehle's area of competence/ownership.

PHP 8.2 support may be interesting, but is not a reason for pressuring maintainers. Please be patient, or use `--ignore-platform-req=php+` during installation on your end :-)

**Comment by driehle** [comment]
5.3.0 is now released, now let's have a look at DoctrineORMModule and DoctrineMongoDBModule for 8.2 releases there.
