### ISSUE TITLE
Current CLI implementation triggers api-tools-mvc-auth events

### ISSUE THREAD

**Issue by tems99** [doctrine/DoctrineModule#802]
Hi,

I am currently using laminas-api-tools with api-tools-mvc-auth. The events in mvc-auth get triggered even for generating proxies. Because the events are triggered, database related code would also be triggered int the case of OAuth2. This then prevents builds like in Docker environments when generating proxies for production.

**Comment by driehle** [comment]
Could you please provide more details on your setup? What command are you running and what is the output?

Technically, api-tools-mvc-auths checks if it runs in a HttpRequest in its boostrapping:

https://github.com/laminas-api-tools/api-tools-mvc-auth/blob/1.8.x/src/Module.php#L79

**Comment by driehle** [comment]
Closing for lack of response. Feel free to re-open, in case the issue persists.
