### ISSUE TITLE
Missing requirement in composer.json

### ISSUE THREAD

**Issue by reinfi** [doctrine/DoctrineModule#808]
Hey,

the latest 6.x version does not work out of the box because of the missing requirement of `composer/semver`. 

Is this expected? There is no hint in the release notes about it. 

`NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class "Composer\Semver\VersionParser" not found in /../vendor/doctrine/doctrine-module/src/ConfigProvider.php:163`

Best regards

**Comment by demiankatz** [comment]
That's not happening for me. What version of Composer are you using? In what context are you seeing this problem?

**Comment by TomHAnderson** [comment]
`vimeo/psalm` requires `composer/semver` so the unit tests are passing, but you are right, @reinfi , we're using VersionParser in the ConfigProvider and without dev options it fails.
