### ISSUE TITLE
Allow cleanSearchValue method to accept an integer

### ISSUE THREAD

**Issue by diego-sorribas** [doctrine/DoctrineModule#818]
Just to understand, why doesn't the cleanSearchValue method in the ObjectExists validator accept an integer? If the purpose of the method is to verify an entity with a given id.

Line: https://github.com/doctrine/DoctrineModule/blob/6.1.x/src/Validator/ObjectExists.php#L128

**Comment by driehle** [comment]
I don't feel like there is a valid reason for this. Feel free to provide a PR to allow int here as well.

**Comment by ekosogin** [comment]
I have the same problem. This method can be used after some filtration (casting to int as example) so without int type backward compatibility from version 5.3 is broken.

**Comment by TomHAnderson** [comment]
I agree that allowing an int is valid input for this Validator.  I'll put this into the next milestone.

**Comment by driehle** [comment]
Closed with #823
