### ISSUE TITLE
Package incorrectly states that it does provide `laminas/laminas-cache-storage-implementation`

### ISSUE THREAD

**Issue by boesing** [doctrine/DoctrineModule#820]
As per `composer.json`, this package is stating that it provides `laminas/laminas-cache-storage-implementation` via `provide`.
Only packages which do actually `provide` an implementation should use `provide`.

There is a good read about dependency inversion [here](https://matthiasnoback.nl/2014/10/composer-provide-and-dependency-inversion/).

Please remove this from the projects `composer.json` to avoid future problems with incompatibilities between `laminas-cache` and `doctrine/doctrine-module`.

**Comment by TomHAnderson** [comment]
100% @boesing Do you want to provide a PR to put your name in the repo?  Else it's a simple fix I'll do promptly.

**Comment by boesing** [comment]
Created #821, feel free to re-target to 6.0.x in case you want to release this as a patch.

**Comment by driehle** [comment]
Closed with #821
