### ISSUE TITLE
Bump to PHP 8.3 ?

### ISSUE THREAD

**Issue by arhimede** [doctrine/DoctrineModule#827]
any chances to bump the  PHP version to 8.3 ?

we have 2 packages which use doctrine-module and are  blocked to be upgraded to 8.3

**Comment by TomHAnderson** [comment]
See https://github.com/doctrine/DoctrineORMModule/pull/749

**Comment by TomHAnderson** [comment]
#828 will move this library to 8.3

**Comment by driehle** [comment]
6.1.0 has been released
